# Load libraries

In [799]:
import pandas as pd 
import numpy as np
import sklearn
import re

# Load datasets

In [800]:
df1 = pd.read_csv("data/ALLARMI.csv")
df2 = pd.read_csv("data/TIPOLOGIA_VIAGGIATORE.csv")

In [801]:
df1

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5075,Nulla a procedere SDI,MXP,LTN,2023,01,2024-01-19 17:30:00,Malpensa,London Luton,Milano,Londra,...,2,5,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,5
5076,Voli disponibili in ingresso al Sistema,BLQ,RAK,2024,02,FEB 06 2024,Guglielmo Marconi,Menara,Bologna,Marrakech,...,8,1,TSC,NaN,NaN,Marocco,ITA,8,Italia,1
5077,Voli con Allarmi,FCO,DOH,2024,01,2024-01-12 15:35:00,Fiumicino,Hamad International,Roma,Doha,...,5,1,NSIS,NaN,NaN,Qatar,ITA,5,Italia,1
5078,"Voli solo visualizzati, ma NON investigati",LIN,LHR,2024,01,2024-01-13 11:50:00,Linate,London Heathrow,Milano,Londra,...,2,1,TSC,NaN,NaN,Regno Unito,ITA,2,Italia,1


In [802]:
df2

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5090,ALB,BLQ,TIA,2024,02,15,2024-02-18 09:10:00,Guglielmo Marconi,Rinas Mother Teresa,Bologna,...,Ryanair DAC,FR8399,NaN,NaN,NaN,N.D.,0-17,ALB,Ryanair DAC,FR8399
5091,ALB,FCO,TIA,2024,01,10,2024-01-10 06:10:00,Fiumicino,Rinas Mother Teresa,Roma,...,Wizz Air Malta,W43857,NaN,NaN,NaN,Passaporto,46-60,ALB,Wizz Air Malta,W43857
5092,ALB,FCO,JED,2024,01,31,31/01/2024 22:15:00,Fiumicino,King Abdulaziz International,Roma,...,Wizz Air Malta,w48350,FERMATO,NaN,NaN,N.D.,31-45,ALB,Wizz Air Malta,w48350
5093,ALB,BGY,TIA,2024,01,1,2024-01-01 08:25:00,Orio al Serio,Rinas Mother Teresa,Bergamo,...,Ryanair DAC,FR8350,IN ATTESA,NaN,NaN,Carta d'identità,18-30,ALB,Ryanair DAC,FR8350


# Allarmi Dataset

First general look at the dataset (df1)

In [803]:
df1.shape

(5080, 24)

In [804]:
df1.head(5)

,OCCORRENZE,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,CITTA_PARTENZA,...,ZONA,TOT,MOTIVO_ALLARME,note_operatore,flag_rischio,Paese Partenza,CODICE PAESE ARR,3zona,paese%arr,tot voli
0,Voli con Allarmi,FCO,IST,2024,01,2024-01-30 09:15:00,Fiumicino,Havalimani,Roma,Istanbul,...,5,1,Manuale,NaN,NaN,Turchia,ITA,5,Italia,1
1,Viaggiatori con Allarmi,CIA,STN,2024,02,2024-02-03 13:15:00,Ciampino,Stansted,Roma,Londra,...,5,5,Manuale,NaN,NaN,Regno Unito,ITA,5,Italia,5
2,Viaggiatori entrati nel Sistema,FCO,LHR,2024,01,2024-01-15 08:45:00,Fiumicino,London Heathrow,Roma,Londra,...,5,110,TSC,NaN,NaN,Regno Unito,ITA,5,Italia,110
3,Voli con Allarmi,MXP,LHR,2024,02,2024-02-02 08:40:00,Malpensa,London Heathrow,Milano,Londra,...,2,1,SDI,NaN,NaN,Regno Unito,ITA,2,Italia,1
4,Viaggiatori con Allarmi,PSA,BRS,2024,02,2024-02-16 12:50:00,Galileo Galilei,Bristol,Pisa,Bristol,...,8,2,INTERPOL,NaN,NaN,Regno Unito,ITA,8,Italia,2


In [805]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5080 entries, 0 to 5079
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   OCCORRENZE             5080 non-null   str  
 1   AREOPORTO_ARRIVO       5080 non-null   str  
 2   AREOPORTO_PARTENZA     5080 non-null   str  
 3   ANNO_PARTENZA          5080 non-null   str  
 4   MESE_PARTENZA          5080 non-null   str  
 5   DATA_PARTENZA          5080 non-null   str  
 6   DESCR_AEREOPORTO_ARR   5080 non-null   str  
 7   DESCR_AEREOPORTO_PART  4971 non-null   str  
 8   CITTA_ARR              5080 non-null   str  
 9   CITTA_PARTENZA         4979 non-null   str  
 10  CODICE_PAESE_ARR       5080 non-null   str  
 11  CODICE_PAESE_PART      5026 non-null   str  
 12  PAESE_ARR              5080 non-null   str  
 13  PAESE_PART             5006 non-null   str  
 14  ZONA                   5080 non-null   str  
 15  TOT                    5080 non-null   str  
 16 

PER ORA HO TOLTO IL DROP DUPLICATES, PERCHE' MAGARI TOGLIAMO RIGHE CHE CI SERVONO

In [806]:
# Normalizing the dataset, lowercasing and stripping useless cases
df1 = df1.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

# Checking for duplicates and dropping them 
#print('Initial duplicates:')
#print(df1.duplicated().sum())
#df1 = df1.drop_duplicates()
#print('Duplicates after cleaning:')
#print(df1.duplicated().sum())


### Occorrenze

In [807]:
print(f"Unique values: {df1['OCCORRENZE'].nunique()}")
print(f"Null values: {df1['OCCORRENZE'].isnull().sum()}")
print()
print(df1['OCCORRENZE'].value_counts(dropna=False).to_string())

Unique values: 30
Null values: 0

OCCORRENZE
viaggiatori entrati nel sistema                 626
voli disponibili in ingresso al sistema         588
voli solo visualizzati, ma non investigati      572
voli investigati (sdi/nsis - interpol - tsc)    543
viaggiatori investigati                         528
allarmi generati da sdi/nsis                    513
voli con allarmi                                507
viaggiatori con allarmi                         468
nulla a procedere sdi                           251
allarmi chiusi                                  245
allarmi rilevanti                               112
errata segnalazione sdi                          25
allarmi generati da bcs                          21
allarmi chiusi con azione (cc.xx)                14
notifica atti/provv                              10
allarmi generati da interpol                      8
allarmi non chiusi                                7
mancato aggiornamento sdi                         6
nulla a procedere n

Grouping categories that are similar to each other

In [808]:
occorrenze_map = {
    'viaggiatori entrati nel sistema'              : 'viaggiatori entrati',
    'voli disponibili in ingresso al sistema'      : 'voli disponibili',
    'voli solo visualizzati, ma non investigati'   : 'voli solo visualizzati',
    'voli investigati (sdi/nsis - interpol - tsc)' : 'voli investigati',
    'viaggiatori investigati'                      : 'viaggiatori investigati',
    'voli con allarmi'                             : 'voli con allarmi',
    'viaggiatori con allarmi'                      : 'viaggiatori con allarmi',
    'allarmi generati da sdi/nsis'                 : 'allarmi generati',
    'allarmi generati da bcs'                      : 'allarmi generati',
    'allarmi generati da interpol'                 : 'allarmi generati',
    'allarmi generati'                             : 'allarmi generati',
    'allarmi chiusi'                               : 'allarmi chiusi',
    'allarmi chiusi con azione (cc.xx)'            : 'allarmi chiusi',
    'allarmi rilevanti'                            : 'allarmi rilevanti',
    'allarmi non chiusi'                           : 'allarmi non chiusi',
    'nulla a procedere sdi'                        : 'esito negativo',
    'nulla a procedere nsis'                       : 'esito negativo',
    'nulla a procedere int'                        : 'esito negativo',
    'errata segnalazione sdi'                      : 'esito negativo',
    'errata segnalazione nsis'                     : 'esito negativo',
    'errata segnalazione bcs'                      : 'esito negativo',
    'respinto/a'                                   : 'esito negativo',
    'mancato aggiornamento sdi'                    : 'mancato aggiornamento',
    'mancato aggiornamento schengen nsis'          : 'mancato aggiornamento',
    'notifica atti/provv'                          : 'altro',
    'inammissibilita schengen - art.24'            : 'altro',
    'altro'                                        : 'altro',
    '???'                                          : np.nan,
    'n/c'                                          : np.nan,
    'ali armatt'                                   : np.nan,
}

df1['OCCORRENZE'] = df1['OCCORRENZE'].map(occorrenze_map)

print(f"\nNull Values: {df1['OCCORRENZE'].isnull().sum()}")
print(f"\nDistribution:")
print(df1['OCCORRENZE'].value_counts(dropna=False).to_string())


Null Values: 3

Distribution:
OCCORRENZE
viaggiatori entrati        626
voli disponibili           588
voli solo visualizzati     572
allarmi generati           547
voli investigati           543
viaggiatori investigati    528
voli con allarmi           507
viaggiatori con allarmi    468
esito negativo             296
allarmi chiusi             259
allarmi rilevanti          112
altro                       16
mancato aggiornamento        8
allarmi non chiusi           7
NaN                          3


In [809]:
df1 = df1.dropna(subset=['OCCORRENZE'])
print(df1.shape)  # deve essere 5027

(5077, 24)


### Aeroporto Arrivo

In [810]:
print(f"Unique values: {df1['AREOPORTO_ARRIVO'].nunique()}")
print(f"Null values: {df1['AREOPORTO_ARRIVO'].isnull().sum()}")
print()
print(df1['AREOPORTO_ARRIVO'].value_counts(dropna=False).to_string())

Unique values: 31
Null values: 0

AREOPORTO_ARRIVO
fco    1281
mxp    1193
bgy     471
vce     359
blq     329
nap     204
lin     175
cia     166
trn     154
psa     140
cta     115
vrn     110
tsf      83
flr      69
bri      57
pmo      26
aoi      24
goa      20
peg      16
psr      16
trs      14
rmi      12
suf       9
pmf       7
cag       7
bds       6
cuf       6
ciy       3
olb       2
bzo       2
vbs       1


In [811]:
# ── df1 – AREOPORTO_PARTENZA ─────────────────────────────────────────────────
print(f"Valori unici: {df1['AREOPORTO_PARTENZA'].nunique()}")
print(f"Valori nulli: {df1['AREOPORTO_PARTENZA'].isnull().sum()}")
print()
print(df1['AREOPORTO_PARTENZA'].value_counts(dropna=False).to_string())

Valori unici: 112
Valori nulli: 0

AREOPORTO_PARTENZA
tia    621
stn    506
lgw    402
lhr    393
ist    301
dxb    153
cai    134
saw    134
cmn    130
man    129
rak    106
doh    105
jfk    104
ssh     96
tun     86
beg     81
auh     78
lcy     74
ewr     63
ltn     60
jed     52
edi     52
gru     51
brs     47
tlv     46
amm     46
add     46
rmo     43
bhx     41
pek     35
evn     32
spx     31
eze     31
pvg     30
icn     29
del     28
tpe     25
alg     25
kwi     23
sin     22
mct     21
ruh     21
ema     18
skp     17
mle     17
szx     17
atl     16
mia     16
gig     16
kiv     15
gyd     15
ncl     15
rmf     15
shj     15
wnz     13
yul     13
bah     13
ika     12
dss     12
kut     12
mex     11
tgd     11
phl     11
fez     10
mba     10
gla     10
hnd     10
lrm      9
hrg      9
sid      9
bqh      9
hkg      8
tng      8
fab      8
dfw      8
prn      8
dwc      8
bey      7
lpl      7
hgh      6
yyz      6
tbs      6
iad      6
adb      6
znz      5
rba      5


### Anno Partenza

In [812]:
print(f"Unique values: {df1['ANNO_PARTENZA'].nunique()}")
print(f"Null values: {df1['ANNO_PARTENZA'].isnull().sum()}")
print()
print(df1['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 5
Null values: 0

ANNO_PARTENZA
2024         4674
2023          257
24             52
anno 2024      52
2024.          42


In [813]:
def normalizza_anno(val):
    if pd.isna(val): return np.nan
    val = str(val).strip()
    match = re.search(r'\b(20\d{2})\b', val)
    if match: return int(match.group(1))
    match = re.search(r'\b(\d{2})\b', val)
    if match: return int('20' + match.group(1))
    return np.nan

df1['ANNO_PARTENZA'] = df1['ANNO_PARTENZA'].apply(normalizza_anno)

print(df1['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

ANNO_PARTENZA
2024    4820
2023     257


### Mese Partenza

In [814]:
print(f"Unique values: {df1['MESE_PARTENZA'].nunique()}")
print(f"Null values: {df1['MESE_PARTENZA'].isnull().sum()}")
print()
print(df1['MESE_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 14
Null values: 0

MESE_PARTENZA
01     2452
02     2289
gen      81
feb      63
12       26
07       23
06       22
04       20
11       20
09       18
08       16
05       16
03       16
10       15


In [815]:
mesi_map = {"gen": "01", "feb": "02"}
df1["MESE_PARTENZA"] = df1["MESE_PARTENZA"].replace(mesi_map)

print(df1["MESE_PARTENZA"].value_counts(dropna=False).sort_index().to_string())

MESE_PARTENZA
01    2533
02    2352
03      16
04      20
05      16
06      22
07      23
08      16
09      18
10      15
11      20
12      26


### Data Partenza

In [816]:
print(f"Unique values: {df1['DATA_PARTENZA'].nunique()}")
print(f"Null values: {df1['DATA_PARTENZA'].isnull().sum()}")
print()
print(df1['DATA_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 3808
Null values: 0

DATA_PARTENZA
2024-02-04 06:10:00    7
2024-02-29 16:40:00    6
2024-01-31 18:00:00    6
2024-01-19 08:55:00    5
2024-01-22 13:00:00    5
2024-02-08 10:00:00    5
2024/02/26             5
2024-01-04 11:30:00    5
2024-01-06 08:00:00    5
2024-01-07 18:00:00    5
2024-02-18 06:50:00    5
2024-02-09 12:50:00    4
05.01.2024             4
2024/02/25             4
gen 06 2024            4
2024-01-05 13:40:00    4
feb 18 2024            4
2024-01-30 12:35:00    4
18.02.2024             4
2024-01-11 14:05:00    4
2024-01-22 07:30:00    4
2024-02-19 09:00:00    4
2024-01-07 17:00:00    4
gen 27 2024            4
2024-02-10 22:20:00    4
gen 14 2024            4
2024-01-12 15:35:00    4
17-01-24               4
2024-02-16 17:30:00    4
2024-02-18 13:05:00    4
2024-01-01 08:00:00    4
2024-02-02 09:15:00    4
2024-01-05 19:05:00    4
2024-01-27 18:05:00    4
23-02-24               4
2024-01-24 08:00:00    4
2024-02-09 18:05:00    4
2024-01-21 17:50:00    4


In [817]:
mesi_ita = {
    "GEN": "01", "FEB": "02", "MAR": "03", "APR": "04",
    "MAG": "05", "GIU": "06", "LUG": "07", "AGO": "08",
    "SET": "09", "OTT": "10", "NOV": "11", "DIC": "12"
}

def normalizza_data(val):
    val = str(val).strip()

    # "GEN 06 2024" → "2024-01-06 00:00:00"
    for ita, num in mesi_ita.items():
        if val.startswith(ita + " "):
            parts = val.split(" ")
            return f"{parts[2]}-{num}-{parts[1].zfill(2)} 00:00:00"

    # "2024-01-05T12:35:00" → "2024-01-05 12:35:00"
    val = val.replace("T", " ")

    # "2024/02/26" o "2024/02/26 09:00:00" → "2024-02-26 00:00:00"
    if re.match(r"\d{4}/\d{2}/\d{2}", val):
        val = val.replace("/", "-")
        if len(val) == 10:
            val = val + " 00:00:00"

    # "05.01.2024" → "2024-01-05 00:00:00"
    match = re.match(r"(\d{2})\.(\d{2})\.(\d{4})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    # "04-01-24" → "2024-01-04 00:00:00"
    match = re.match(r"(\d{2})-(\d{2})-(\d{2})$", val)
    if match:
        return f"20{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    # "22/01/2024 15:45:00" → "2024-01-22 15:45:00"
    match = re.match(r"(\d{2})/(\d{2})/(\d{4})\s(\d{2}:\d{2}:\d{2})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} {match.group(4)}"

    return val

df1["DATA_PARTENZA"] = df1["DATA_PARTENZA"].apply(normalizza_data)
df1["DATA_PARTENZA"] = pd.to_datetime(df1["DATA_PARTENZA"], errors="coerce")


# Recover NaT rows using ANNO_PARTENZA + MESE_PARTENZA (set to 1st of the month)
nat_mask = df1["DATA_PARTENZA"].isnull()
df1.loc[nat_mask, "DATA_PARTENZA"] = pd.to_datetime(
    df1.loc[nat_mask, "ANNO_PARTENZA"].astype(str) + "-" +
    df1.loc[nat_mask, "MESE_PARTENZA"].astype(str).str.zfill(2) + "-01",
    errors="coerce"
)

print("NaT left:", df1["DATA_PARTENZA"].isnull().sum())
print("Range date:", df1["DATA_PARTENZA"].min(), "→", df1["DATA_PARTENZA"].max())
print("Examples:")
print(df1["DATA_PARTENZA"].head(5).to_string())

NaT left: 0
Range date: 2023-01-01 00:00:00 → 2024-12-01 00:00:00
Examples:
0   2024-01-30 09:15:00
1   2024-02-03 13:15:00
2   2024-01-15 08:45:00
3   2024-02-02 08:40:00
4   2024-02-16 12:50:00


### Descr Aeroporto Arr

In [818]:
print(f"Unique values: {df1['DESCR_AEREOPORTO_ARR'].nunique()}")
print(f"Null values: {df1['DESCR_AEREOPORTO_ARR'].isnull().sum()}")
print()
print(df1['DESCR_AEREOPORTO_ARR'].value_counts(dropna=False).to_string())

Unique values: 31
Null values: 0

DESCR_AEREOPORTO_ARR
fiumicino               1281
malpensa                1193
orio al serio            471
venezia marco polo       359
guglielmo marconi        329
napoli capodichino       204
linate                   175
ciampino                 166
sandro pertini           154
galileo galilei          140
fontanarossa             115
verona villafranca       110
treviso-sant'angelo       83
firenze peretola          69
palese                    57
punta raisi               26
falconara                 24
cristoforo colombo        20
sant egidio               16
liberi                    16
ronchi dei legionari      14
miramare                  12
lamezia terme              9
parma                      7
elmas                      7
papola casale              6
levaldigi                  6
comiso                     3
costa smeralda             2
bolzano                    2
brescia montichiari        1


### Descr Aeroporto Part

In [819]:
print(f"Unique values: {df1['DESCR_AEREOPORTO_PART'].nunique()}")
print(f"Null values: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print()
print(df1['DESCR_AEREOPORTO_PART'].value_counts(dropna=False).to_string())

Unique values: 119
Null values: 109

DESCR_AEREOPORTO_PART
rinas mother teresa                                                  584
stansted                                                             476
london gatwick                                                       382
london heathrow                                                      370
havalimani                                                           285
dubai international                                                  142
cairo international                                                  127
sabiha gokcen                                                        127
manchester                                                           122
mohamed v                                                            120
NaN                                                                  109
hamad international                                                  102
menara                                                           

The column contained 3 types of issues:

1. **167 rows with extra whitespace** — fixed with `.str.strip()`

2. **83 placeholder values** — values such as `"n.d."`, `"nd"`, `"unknown"`, `"null"`
   that carry no real information but were written as text instead of
   being left empty. Converted to `pd.NA` using `.replace()`.

3. **109 original nulls** — empty cells already present in the dataset.

Points 2 and 3 brought the total null count to 192 (3.8% of rows).
All 192 were **recovered** using the IATA code present in the
`AREOPORTO_PARTENZA` column: through an IATA → full airport name
lookup table, each null was replaced with the correct name in lowercase
(e.g. `"STN"` → `"stansted"`, `"LHR"` → `"london heathrow"`).

**Final result: 0 nulls, 133 unique values, all lowercase.**

In [820]:
# ── Dizionario IATA → nome descrittivo ───────────────────────────────────────

PLACEHOLDER_NULL = {'n.d.', '?', '', '//', '-', 'unknown', 'nd', 'n/a', 'null', 'anu', 'none'}

# Prendo solo le righe dove il nome descrittivo è valido (non placeholder)
df1_validi = df1[~df1['DESCR_AEREOPORTO_PART'].isin(PLACEHOLDER_NULL) & df1['DESCR_AEREOPORTO_PART'].notna()]

iata_to_name = (
    df1_validi
    .groupby('AREOPORTO_PARTENZA')['DESCR_AEREOPORTO_PART']
    .agg(lambda x: x.mode()[0])
    .to_dict()
)

print(f" Dizionario creato: {len(iata_to_name)} aeroporti mappati")

df1['DESCR_AEREOPORTO_PART'] = df1['DESCR_AEREOPORTO_PART'].apply(
    lambda x: np.nan if str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulli dopo sostituzione placeholder: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")

df1['DESCR_AEREOPORTO_PART'] = df1.apply(
    lambda row: iata_to_name.get(row['AREOPORTO_PARTENZA'], row['AREOPORTO_PARTENZA'])
    if pd.isna(row['DESCR_AEREOPORTO_PART'])
    else row['DESCR_AEREOPORTO_PART'],
    axis=1
)

print(f"Nulli rimasti: {df1['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print(df1['DESCR_AEREOPORTO_PART'].value_counts(dropna=False).to_string())

 Dizionario creato: 111 aeroporti mappati
Nulli dopo sostituzione placeholder: 309
Nulli rimasti: 0
DESCR_AEREOPORTO_PART
rinas mother teresa                                                  621
stansted                                                             506
london gatwick                                                       402
london heathrow                                                      393
havalimani                                                           301
dubai international                                                  153
cairo international                                                  134
sabiha gokcen                                                        134
mohamed v                                                            130
manchester                                                           129
menara                                                               106
hamad international                                                  105
jo

### Città Arrivo

In [821]:
print(f"Unique values: {df1['CITTA_ARR'].nunique()}")
print(f"Null values: {df1['CITTA_ARR'].isnull().sum()}")
print()
print(df1['CITTA_ARR'].value_counts(dropna=False).to_string())

Unique values: 29
Null values: 0

CITTA_ARR
roma             1447
milano           1368
bergamo           471
venezia           359
bologna           329
napoli            204
torino            154
pisa              140
catania           115
verona            110
treviso            83
firenze            69
bari               57
palermo            26
ancona             24
genova             20
perugia            16
pescara            16
trieste            14
rimini             12
lamezia terme       9
parma               7
cagliari            7
brindisi            6
cuneo               6
comiso              3
olbia               2
bolzano             2
brescia             1


### Città Partenza

In [822]:
print(f"Unique values: {df1['CITTA_PARTENZA'].nunique()}")
print(f"Null values: {df1['CITTA_PARTENZA'].isnull().sum()}")
print()
print(df1['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 110
Null values: 101

CITTA_PARTENZA
londra               1376
tirana                590
istanbul              411
dubai                 152
cairo                 126
manchester            124
casablanca            120
marrakech             103
NaN                   101
doha                   99
new york               99
sharm el sheikh        89
tunis                  81
belgrado               80
abu dhabi              74
newark                 57
chisinau               55
edinburgh              52
jeddah                 50
san paolo              48
bristol                46
tel aviv yafo          45
amman                  43
addis ababa            41
birmingham             38
pechino                34
n.d.                   31
yerevan                31
seoul                  29
buenos aires           29
shanghai               29
giza                   28
nuova delhi            27
algeri                 25
taipei                 24
?                      24
nd          

In [823]:
# ── Replace placeholder values with NaN, then recover via IATA lookup ────────

PLACEHOLDER_NULL = {'n.d.', '?', '', '//', '-', 'unknown', 'nd', 'n/a', 'null', 'anu', 'none'}

df1["CITTA_PARTENZA"] = df1["CITTA_PARTENZA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df1['CITTA_PARTENZA'].isnull().sum()}")

# Recover nulls via IATA → city lookup
iata_city = {
    "tia": "tirana",   "stn": "londra",    "lgw": "londra",   "lhr": "londra",
    "lcy": "londra",   "ltn": "londra",    "bqh": "londra",   "fab": "londra",
    "ist": "istanbul", "dxb": "dubai",     "cai": "il cairo", "saw": "istanbul",
    "cmn": "casablanca","doh": "doha",      "rak": "marrakech","jfk": "new york",
    "ssh": "sharm el-sheikh","tun": "tunisi","beg": "belgrado","auh": "abu dhabi",
    "ewr": "new york", "jed": "jeddah",    "edi": "edinburgo","gru": "san paolo",
    "eze": "buenos aires","add": "addis abeba","mex": "citta del messico",
    "pek": "pechino",  "rmo": "chisinau",  "bhx": "birmingham","pvg": "shanghai",
    "hkg": "hong kong","mct": "muscat",    "mle": "male",     "rba": "rabat",
    "evn": "yerevan",  "tbs": "tbilisi",   "ema": "east midlands","ruh": "riad",
    "shj": "sharjah",  "gla": "glasgow",   "icn": "seul",     "rmf": "marsa alam",
    "tng": "tangeri",  "sid": "praia",     "spx": "cairo",    "ika": "teheran",
    "prn": "pristina", "mba": "mombasa",   "szx": "shenzhen", "mia": "miami",
    "tpe": "taipei",   "sin": "singapore", "tlv": "tel aviv", "amm": "amman",
    "brs": "bristol",  "man": "manchester","anu": "saint john's","ncl": "newcastle",
    "del": "nuova delhi","atl": "atlanta", "kwi": "kuwait",   "dfw": "dallas",
    "iad": "washington","yul": "montreal", "yyz": "toronto",  "hnd": "tokyo",
    "bey": "beirut",   "alg": "algeri",    "kiv": "chisinau", "gyd": "baku",
    "lpl": "liverpool","skp": "skopje",    "tgd": "podgorica","phl": "filadelfia",
    "fez": "fez",      "gig": "rio de janeiro","atq": "amritsar","znz": "zanzibar",
    "nkg": "nanchino", "aga": "agadir",    "mji": "misurata", "dmm": "dammam",
    "ckg": "chongqing","bfs": "belfast",   "bos": "boston",   "lxr": "luxor",
    "can": "guangzhou","wnz": "wenzhou",   "hgh": "hangzhou", "bah": "manama",
    "dss": "dakar",    "kut": "kutaisi",   "hrg": "hurghada", "lrm": "al marj",
    "oak": "oakland",  "lax": "los angeles","oxf": "oxford",  "lba": "leeds",
    "ala": "almaty",   "isl": "islamabad", "lyx": "marsa matruh","nht": "londra",
    "mbj": "montego bay","cun": "cancun",  "mru": "port louis","tas": "tashkent",
    "sll": "freetown", "cgo": "zhengzhou", "tfu": "chengdu",  "lyx": "marsa matruh",
}

null_mask = df1["CITTA_PARTENZA"].isnull()
df1.loc[null_mask, "CITTA_PARTENZA"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"]
    .str.strip().str.lower()
    .map(iata_city)
)

# Fallback: recover any remaining nulls from other rows sharing the same IATA code
iata_city_from_data = (
    df1[df1["CITTA_PARTENZA"].notna()]
    .groupby("AREOPORTO_PARTENZA")["CITTA_PARTENZA"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df1["CITTA_PARTENZA"].isnull()
df1.loc[null_mask, "CITTA_PARTENZA"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_city_from_data)
)

print(f"Null left: {df1['CITTA_PARTENZA'].isnull().sum()}")
print(f"Unique values: {df1['CITTA_PARTENZA'].nunique()}")

print(df1['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

Nulls after placeholder cleanup: 253
Null left: 0
Unique values: 113
CITTA_PARTENZA
londra               1445
tirana                621
istanbul              436
dubai                 161
casablanca            130
cairo                 129
manchester            129
new york              110
marrakech             106
doha                  105
sharm el sheikh        89
tunis                  81
belgrado               81
abu dhabi              78
chisinau               58
newark                 57
jeddah                 52
edinburgh              52
san paolo              51
bristol                47
amman                  46
tel aviv yafo          45
birmingham             41
addis ababa            41
pechino                35
yerevan                32
buenos aires           31
shanghai               30
seoul                  29
giza                   28
nuova delhi            28
taipei                 25
algeri                 25
singapore              22
kuwait city            22
muscat

### Codice Paese Arrivo / Partenza

In [824]:
print("--- CODICE_PAESE_ARR ---")
print(f"Unique: {df1['CODICE_PAESE_ARR'].nunique()}  |  Null: {df1['CODICE_PAESE_ARR'].isnull().sum()}")
print(df1['CODICE_PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- CODICE_PAESE_PART ---")
print(f"Unique: {df1['CODICE_PAESE_PART'].nunique()}  |  Null: {df1['CODICE_PAESE_PART'].isnull().sum()}")
print(df1['CODICE_PAESE_PART'].value_counts(dropna=False).to_string())

--- CODICE_PAESE_ARR ---
Unique: 8  |  Null: 0
CODICE_PAESE_ARR
ita    4734
it      251
fra      25
gbr      18
esp      18
tur      17
deu      13
gb        1

--- CODICE_PAESE_PART ---
Unique: 67  |  Null: 54
CODICE_PAESE_PART
gbr        1644
alb         558
tur         410
egy         262
mar         255
are         235
usa         215
chn         116
qat         101
tun          83
gb           80
srb          79
sau          75
bra          65
mda          58
NaN          54
eth          46
jor          45
isr          44
al           36
arg          30
arm          29
ind          28
kor          26
dza          25
tr           24
unknown      24
twn          23
omn          23
sgp          22
kwt          22
can          18
mkd          17
eg           17
geo          17
mdv          16
             16
aze          15
nd           14
n.d.         13
mex          13
bhr          13
//           13
irn          12
?            12
sen          12
ae           12
mne          11
ken

In [825]:
# Cross-check: AREOPORTO_ARRIVO contains only Italian airports, so CODICE_PAESE_ARR
# must be Italy for every row. Any non-"ita" value is a data-entry error.
# We overwrite the entire column rather than mapping variants, since the ground
# truth (Italian arrival airport) is unambiguous.

n_wrong = (df1["CODICE_PAESE_ARR"] != "ita").sum()
print(f"Rows with non-'ita' value before fix: {n_wrong}")
if n_wrong > 0:
    print(df1.loc[df1["CODICE_PAESE_ARR"] != "ita", "CODICE_PAESE_ARR"].value_counts().to_string())

df1["CODICE_PAESE_ARR"] = "ita"

print(f"\nUnique values after fix: {df1['CODICE_PAESE_ARR'].nunique()}")
print(df1["CODICE_PAESE_ARR"].value_counts().to_string())

# CODICE_PAESE_PART: recover nulls using IATA → ISO-3 country code lookup.
iata_country_code = {
    "tia": "alb", "stn": "gbr", "lgw": "gbr", "lhr": "gbr", "lcy": "gbr",
    "ltn": "gbr", "bqh": "gbr", "fab": "gbr", "nht": "gbr", "lpl": "gbr",
    "ncl": "gbr", "edi": "gbr", "bhx": "gbr", "gla": "gbr", "bfs": "gbr",
    "lba": "gbr", "ema": "gbr", "brs": "gbr", "man": "gbr", "oxf": "gbr",
    "ist": "tur", "saw": "tur", "adb": "tur",
    "dxb": "are", "shj": "are", "auh": "are", "dwc": "are",
    "cai": "egy", "ssh": "egy", "hrg": "egy", "lxr": "egy", "rmf": "egy",
    "cmn": "mar", "rak": "mar", "tng": "mar", "fez": "mar", "aga": "mar", "rba": "mar",
    "doh": "qat",
    "jfk": "usa", "ewr": "usa", "mia": "usa", "atl": "usa", "dfw": "usa",
    "iad": "usa", "bos": "usa", "phl": "usa", "oak": "usa", "lax": "usa",
    "tun": "tun", "beg": "srb",
    "jed": "sau", "ruh": "sau", "dmm": "sau",
    "gru": "bra", "gig": "bra",
    "eze": "arg", "add": "eth",
    "mex": "mex", "cun": "mex",
    "pek": "chn", "pvg": "chn", "szx": "chn", "can": "chn", "wnz": "chn",
    "hgh": "chn", "nkg": "chn", "cgo": "chn", "tfu": "chn", "ckg": "chn",
    "rmo": "mda", "kiv": "mda",
    "hkg": "hkg", "mct": "omn", "mle": "mdv", "evn": "arm",
    "tbs": "geo", "kut": "geo", "icn": "kor", "sid": "cpv", "spx": "egy",
    "ika": "irn", "prn": "xkx", "mba": "ken", "znz": "tza",
    "tpe": "twn", "sin": "sgp", "tlv": "isr", "amm": "jor",
    "del": "ind", "atq": "ind", "kwi": "kwt",
    "yul": "can", "yyz": "can", "hnd": "jpn", "bey": "lbn", "alg": "dza",
    "gyd": "aze", "skp": "mkd", "tgd": "mne", "anu": "atg", "dss": "sen",
    "bah": "bhr", "lrm": "lby", "mji": "lby", "mbj": "jam", "mru": "mus",
    "tas": "uzb", "sll": "sle", "ala": "kaz", "isl": "pak",
}

null_mask = df1["CODICE_PAESE_PART"].isnull()
df1.loc[null_mask, "CODICE_PAESE_PART"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"]
    .str.strip().str.lower()
    .map(iata_country_code)
)

print(f"\nNull left CODICE_PAESE_PART: {df1['CODICE_PAESE_PART'].isnull().sum()}")
print(df1['CODICE_PAESE_PART'].value_counts(dropna=False).head(15).to_string())

Rows with non-'ita' value before fix: 343
CODICE_PAESE_ARR
it     251
fra     25
gbr     18
esp     18
tur     17
deu     13
gb       1

Unique values after fix: 1
CODICE_PAESE_ARR
ita    5077

Null left CODICE_PAESE_PART: 0
CODICE_PAESE_PART
gbr    1666
alb     567
tur     414
egy     265
mar     255
are     237
usa     219
chn     118
qat     102
tun      83
gb       80
srb      80
sau      75
bra      66
mda      58


### Paese Arrivo / Partenza

In [826]:
print("--- PAESE_ARR ---")
print(f"Unique: {df1['PAESE_ARR'].nunique()}  |  Null: {df1['PAESE_ARR'].isnull().sum()}")
print(df1['PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- PAESE_PART ---")
print(f"Unique: {df1['PAESE_PART'].nunique()}  |  Null: {df1['PAESE_PART'].isnull().sum()}")
print(df1['PAESE_PART'].value_counts(dropna=False).to_string())

--- PAESE_ARR ---
Unique: 1  |  Null: 0
PAESE_ARR
italia    5077

--- PAESE_PART ---
Unique: 57  |  Null: 74
PAESE_PART
regno unito              1714
albania                   596
turchia                   424
egitto                    270
marocco                   257
emirati arabi uniti       244
stati uniti               220
cina                      117
qatar                     101
tunisia                    81
serbia                     80
arabia saudita             76
NaN                        74
brasile                    62
moldavia                   56
giordania                  45
etiopia                    44
israele                    43
argentina                  30
india                      30
armenia                    29
corea del sud              28
algeria                    24
taiwan                     22
oman                       22
kuwait                     22
singapore                  21
nd                         21
//                         21
?         

In [827]:
# PAESE_ARR: always Italy — no action needed.
# PAESE_PART: first replace placeholders with NaN, then recover via ISO-3 lookup.

PLACEHOLDER_NULL = {'n.d.', '?', '', '//', '-', 'unknown', 'nd', 'n/a', 'null', 'anu', 'none'}

df1["PAESE_PART"] = df1["PAESE_PART"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df1['PAESE_PART'].isnull().sum()}")

codice_paese_map = {
    "alb": "albania",          "gbr": "regno unito",      "tur": "turchia",
    "are": "emirati arabi",    "egy": "egitto",            "mar": "marocco",
    "qat": "qatar",            "usa": "stati uniti",       "tun": "tunisia",
    "srb": "serbia",           "sau": "arabia saudita",    "bra": "brasile",
    "arg": "argentina",        "eth": "etiopia",           "mex": "messico",
    "chn": "cina",             "mda": "moldavia",          "hkg": "hong kong",
    "omn": "oman",             "mdv": "maldive",           "arm": "armenia",
    "geo": "georgia",          "kor": "corea del sud",     "cpv": "capo verde",
    "irn": "iran",             "xkx": "kosovo",            "ken": "kenya",
    "tza": "tanzania",         "twn": "taiwan",            "sgp": "singapore",
    "isr": "israele",          "jor": "giordania",         "ind": "india",
    "kwt": "kuwait",           "can": "canada",            "jpn": "giappone",
    "lbn": "libano",           "dza": "algeria",           "aze": "azerbaigian",
    "mkd": "macedonia",        "mne": "montenegro",        "atg": "antigua",
    "sen": "senegal",          "bhr": "bahrein",           "lby": "libia",
    "jam": "giamaica",         "mus": "mauritius",         "uzb": "uzbekistan",
    "sle": "sierra leone",     "kaz": "kazakistan",        "pak": "pakistan",
}

null_mask = df1["PAESE_PART"].isnull()
df1.loc[null_mask, "PAESE_PART"] = (
    df1.loc[null_mask, "CODICE_PAESE_PART"]
    .str.strip().str.lower()
    .map(codice_paese_map)
)

# Fallback: recover any remaining nulls from other rows sharing the same IATA code
iata_paese_from_data = (
    df1[df1["PAESE_PART"].notna()]
    .groupby("AREOPORTO_PARTENZA")["PAESE_PART"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df1["PAESE_PART"].isnull()
df1.loc[null_mask, "PAESE_PART"] = (
    df1.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_paese_from_data)
)

print(f"Null left PAESE_PART: {df1['PAESE_PART'].isnull().sum()}")
print(df1['PAESE_PART'].value_counts(dropna=False).head(30).to_string())

Nulls after placeholder cleanup: 203
Null left PAESE_PART: 0
PAESE_PART
regno unito            1779
albania                 621
turchia                 442
egitto                  288
marocco                 264
emirati arabi uniti     244
stati uniti             229
cina                    120
qatar                   105
tunisia                  86
serbia                   81
arabia saudita           77
brasile                  67
moldavia                 58
israele                  46
giordania                46
etiopia                  46
india                    32
armenia                  32
argentina                31
corea del sud            29
taiwan                   25
algeria                  25
oman                     24
kuwait                   23
singapore                22
canada                   19
georgia                  18
macedonia                17
maldive                  17


### Zona

In [828]:
print(f"Unique values: {df1['ZONA'].nunique()}")
print(f"Null values: {df1['ZONA'].isnull().sum()}")
print()
print(df1['ZONA'].value_counts(dropna=False).sort_index().to_string())

Unique values: 12
Null values: 0

ZONA
-1       3
1      180
10       1
2     1837
4      565
5     1470
6      212
7      144
8      580
9       79
99       1
??       5


In [829]:
# -1 is not a valid zone — treat it as missing before casting to integer.
df1["ZONA"] = df1["ZONA"].replace("-1", np.nan)
df1["ZONA"] = pd.to_numeric(df1["ZONA"], errors="coerce")
df1.loc[df1["ZONA"] == -1, "ZONA"] = np.nan   # catch numeric -1 if already parsed
df1["ZONA"] = df1["ZONA"].astype(pd.Int64Dtype())

print(f"Null left (were -1): {df1['ZONA'].isnull().sum()}")
print(f"dtype: {df1['ZONA'].dtype}")
print(df1["ZONA"].value_counts(dropna=False).sort_index().to_string())

Null left (were -1): 8
dtype: Int64
ZONA
1        180
2       1837
4        565
5       1470
6        212
7        144
8        580
9         79
10         1
99         1
<NA>       8


### TOT

In [830]:
print(f"Unique values: {df1['TOT'].nunique()}")
print(f"Null values: {df1['TOT'].isnull().sum()}")
print()
print(df1['TOT'].value_counts(dropna=False).head(20).to_string())

Unique values: 347
Null values: 0

TOT
1       2368
2        178
3        149
4        114
7         86
5         83
8         76
6         68
10        50
9         48
0         41
?         40
15        40
n.d.      35
16        34
12        32
11        32
14        31
18        29
13        27


In [831]:
# Cast to integer, recovering nulls from the duplicate column "tot voli" first.
df1["TOT"] = pd.to_numeric(df1["TOT"], errors="coerce")

null_mask = df1["TOT"].isnull()
print(f"Nulls after initial parse: {null_mask.sum()}")

df1.loc[null_mask, "TOT"] = pd.to_numeric(df1.loc[null_mask, "tot voli"], errors="coerce")
print(f"Nulls after recovery from 'tot voli': {df1['TOT'].isnull().sum()}")

# Null out impossible values: negatives and 99999 (error placeholder)
n_negative = (df1["TOT"] < 0).sum()
n_placeholder = (df1["TOT"] == 99999).sum()
df1.loc[df1["TOT"] < 0, "TOT"] = np.nan
df1.loc[df1["TOT"] == 99999, "TOT"] = np.nan
print(f"Nulled out: {n_negative} negative value(s), {n_placeholder} placeholder(s) (99999)")

# pd.to_numeric returns float64 (NaN forces floats); go through nullable Float64
# first so pandas can safely promote NA before converting to nullable Int64.
df1["TOT"] = df1["TOT"].astype("Float64").astype("Int64")

print(f"Null left: {df1['TOT'].isnull().sum()}")
print(f"dtype: {df1['TOT'].dtype}")
print(f"Min: {df1['TOT'].min()}  |  Max: {df1['TOT'].max()}  |  Mean: {df1['TOT'].mean():.1f}")

Nulls after initial parse: 156
Nulls after recovery from 'tot voli': 156
Nulled out: 7 negative value(s), 2 placeholder(s) (99999)
Null left: 165
dtype: Int64
Min: 0  |  Max: 10000  |  Mean: 44.7


In [832]:
df1 = df1.dropna(subset=['TOT'])
print(df1.shape)  # deve essere 4863

(4912, 24)


### Motivo Allarme

In [833]:
print(f"Unique values: {df1['MOTIVO_ALLARME'].nunique()}")
print(f"Null values: {df1['MOTIVO_ALLARME'].isnull().sum()}")
print()
print(df1['MOTIVO_ALLARME'].value_counts(dropna=False).to_string())

Unique values: 5
Null values: 1115

MOTIVO_ALLARME
NaN         1115
sdi          797
tsc          788
manuale      753
nsis         736
interpol     723


In [834]:
# Standardise category labels.
motivo_map = {
    "sdi"      : "sdi",
    "nsis"     : "nsis",
    "sdi/nsis" : "sdi/nsis",
    "tsc"      : "tsc",
    "interpol" : "interpol",
    "bcs"      : "bcs",
    "manuale"  : "manuale",
}

df1["MOTIVO_ALLARME"] = df1["MOTIVO_ALLARME"].map(lambda x: motivo_map.get(str(x).strip(), np.nan) if pd.notna(x) else np.nan)

print(f"Null left: {df1['MOTIVO_ALLARME'].isnull().sum()}")
print(df1["MOTIVO_ALLARME"].value_counts(dropna=False).to_string())

Null left: 1115
MOTIVO_ALLARME
NaN         1115
sdi          797
tsc          788
manuale      753
nsis         736
interpol     723


### Note Operatore

In [835]:
print(f"Unique values: {df1['note_operatore'].nunique()}")
print(f"Null values: {df1['note_operatore'].isnull().sum()}  ({df1['note_operatore'].isnull().mean()*100:.1f}%)")
print()
print(df1['note_operatore'].value_counts(dropna=False).head(15).to_string())

Unique values: 4
Null values: 4838  (98.5%)

note_operatore
NaN                   4838
passeggero noto         21
alert manuale           20
doppio controllo        17
verifica richiesta      16


### Flag Rischio

In [836]:
print(f"Unique values: {df1['flag_rischio'].nunique()}")
print(f"Null values: {df1['flag_rischio'].isnull().sum()}  ({df1['flag_rischio'].isnull().mean()*100:.1f}%)")
print()
print(df1['flag_rischio'].value_counts(dropna=False).to_string())

Unique values: 2
Null values: 4861  (99.0%)

flag_rischio
NaN      4861
alto       27
medio      24


### Colonne Duplicate

In [837]:
# The duplicate columns may use different formatting (case, punctuation, encoding)
# from their cleaned counterparts. Normalise both sides before comparing.

def norm_str(s):
    """Lowercase, strip whitespace and trailing dots; treat null-like strings as empty."""
    if pd.isna(s):
        return ""
    s = str(s).strip().lower().rstrip(".")
    return "" if s in {"nan", "none", "n/a", "nd", "n.d.", "<na>"} else s

str_checks = [
    ("Paese Partenza",   "PAESE_PART"),
    ("CODICE PAESE ARR", "CODICE_PAESE_ARR"),
    ("paese%arr",        "PAESE_ARR"),
]

for dup, orig in str_checks:
    nd = df1[dup].map(norm_str)
    no = df1[orig].map(norm_str)
    n_mismatch = (nd != no).sum()
    print(f"'{dup}' ~= '{orig}':  {n_mismatch} mismatches out of {len(df1)}")
    if n_mismatch > 0 and n_mismatch <= 10:
        print(df1.loc[nd != no, [dup, orig]].to_string())
    elif n_mismatch > 10:
        print("  sample differences:")
        print(df1.loc[nd != no, [dup, orig]].head(5).to_string())

# Numeric check: tot voli (str) vs TOT (Int64)
n_mismatch_tot = (
    pd.to_numeric(df1["tot voli"], errors="coerce") != df1["TOT"].astype(float)
).sum()
print(f"\n'tot voli' ~= 'TOT':  {n_mismatch_tot} mismatches")

# Integer check: 3zona (int64) vs ZONA (Int64, -1 → NaN)
# For rows where ZONA is NA (was -1), '3zona' should have -1 → skip those
valid = df1["ZONA"].notna()
n_mismatch_zona = (df1.loc[valid, "3zona"] != df1.loc[valid, "ZONA"].astype(int)).sum()
na_zona = (~valid).sum()
print(f"'3zona' ~= 'ZONA':  {n_mismatch_zona} mismatches on valid rows  ({na_zona} rows had -1 → NaN)")

'Paese Partenza' ~= 'PAESE_PART':  10 mismatches out of 4912
           Paese Partenza     PAESE_PART
348   emirati arabi uniti  emirati arabi
553   emirati arabi uniti  emirati arabi
575   emirati arabi uniti  emirati arabi
1169  emirati arabi uniti  emirati arabi
1783  emirati arabi uniti  emirati arabi
2871  emirati arabi uniti  emirati arabi
3390  emirati arabi uniti  emirati arabi
3462  emirati arabi uniti  emirati arabi
3910  emirati arabi uniti  emirati arabi
4339  emirati arabi uniti  emirati arabi
'CODICE PAESE ARR' ~= 'CODICE_PAESE_ARR':  0 mismatches out of 4912
'paese%arr' ~= 'PAESE_ARR':  0 mismatches out of 4912

'tot voli' ~= 'TOT':  36 mismatches
'3zona' ~= 'ZONA':  2 mismatches on valid rows  (8 rows had -1 → NaN)


In [838]:
# Drop duplicate and redundant columns.
cols_to_drop = [
    # Original duplicate columns
    "Paese Partenza", "CODICE PAESE ARR", "3zona", "paese%arr", "tot voli",
    # Airport descriptions: redundant with IATA codes
    "DESCR_AEREOPORTO_ARR", "DESCR_AEREOPORTO_PART",
    # Arrival country: always "italia"/"ita" — zero variance
    "CODICE_PAESE_ARR", "PAESE_ARR",
    # Departure country: keep PAESE_PART, drop ISO-3 code
    "CODICE_PAESE_PART",
    # Date: ANNO and MESE are subsumed by DATA_PARTENZA (NaT rows already recovered above)
    "ANNO_PARTENZA", "MESE_PARTENZA",
]
df1.drop(columns=cols_to_drop, inplace=True)

print(f"Remaining columns ({df1.shape[1]}):")
print(df1.columns.tolist())

Remaining columns (12):
['OCCORRENZE', 'AREOPORTO_ARRIVO', 'AREOPORTO_PARTENZA', 'DATA_PARTENZA', 'CITTA_ARR', 'CITTA_PARTENZA', 'PAESE_PART', 'ZONA', 'TOT', 'MOTIVO_ALLARME', 'note_operatore', 'flag_rischio']


In [839]:
key = ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO', 'DATA_PARTENZA', 'OCCORRENZE', 'MOTIVO_ALLARME']
df1 = df1.groupby(key, dropna=False).agg(
    TOT=('TOT', 'max'),
    CITTA_ARR=('CITTA_ARR', 'first'),
    CITTA_PARTENZA=('CITTA_PARTENZA', 'first'),
    PAESE_PART=('PAESE_PART', 'first'),
    ZONA=('ZONA', 'first'),
    note_operatore=('note_operatore', 'first'),
    flag_rischio=('flag_rischio', 'first')
).reset_index()

print(df1.shape)

(4832, 12)


In [840]:
df1

,AREOPORTO_PARTENZA,AREOPORTO_ARRIVO,DATA_PARTENZA,OCCORRENZE,MOTIVO_ALLARME,TOT,CITTA_ARR,CITTA_PARTENZA,PAESE_PART,ZONA,note_operatore,flag_rischio
0,adb,mxp,2024-01-04 11:45:00,viaggiatori con allarmi,manuale,3,milano,smirne,turchia,2,NaN,NaN
1,adb,mxp,2024-01-04 11:45:00,viaggiatori investigati,NaN,171,milano,smirne,turchia,2,NaN,NaN
2,adb,mxp,2024-01-08 11:45:00,allarmi generati,NaN,5,milano,smirne,turchia,2,NaN,NaN
3,adb,mxp,2024-02-12 11:45:00,voli con allarmi,tsc,1,milano,smirne,turchia,2,NaN,NaN
4,adb,mxp,2024-02-15 11:45:00,voli investigati,nsis,1,milano,smirne,turchia,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4827,yyz,mxp,2024-02-15 16:05:00,voli disponibili,sdi,1,milano,toronto,canada,2,NaN,NaN
4828,znz,fco,2024-01-03 08:30:00,voli con allarmi,manuale,1,roma,zanzibar,tanzania,5,NaN,NaN
4829,znz,fco,2024-01-09 00:00:00,viaggiatori entrati,sdi,358,roma,zanzibar,tanzania,5,NaN,NaN
4830,znz,fco,2024-02-21 08:30:00,allarmi chiusi,manuale,22,roma,zanzibar,tanzania,5,NaN,NaN


# Tipologia Viaggiatore Dataset

First general look at the dataset (df2)

In [841]:
df2.shape

(5095, 33)

In [842]:
df2.head(5)

,NAZIONALITA,AREOPORTO_ARRIVO,AREOPORTO_PARTENZA,ANNO_PARTENZA,MESE_PARTENZA,GIORNO_PARTENZA,DATA_PARTENZA,DESCR_AEREOPORTO_ARR,DESCR_AEREOPORTO_PART,CITTA_ARR,...,COMPAGNIA_AEREA,NUMERO_VOLO,ESITO_CONTROLLO,note_operatore,codice_rischio,Tipo Documento,FASCIA ETA,3nazionalita,compagnia%aerea,num volo
0,ALB,NAP,DUR,2024,02,13,2024-02-13 07:30:00,Napoli Capodichino,King Shaka International,Napoli,...,Fly Dubai,FZ1681,RESPINTO,NaN,NaN,Passaporto,N.D.,ALB,Fly Dubai,FZ1681
1,NaN,FCO,JFK,2024,01,22,2024-01-22 16:35:00,Fiumicino,John F Kennedy International,Roma,...,ITA Airways,AZ0609,NaN,NaN,NaN,Carta d'identità,18-30,ALB,ITA Airways,AZ0609
2,ALB,TSF,TIA,2024,02,4,2024-02-04 20:10:00,Treviso-Sant'Angelo,Rinas Mother Teresa,Treviso,...,Ryanair DAC,FR8400,SEGNALATO,NaN,NaN,N.D.,31-45,ALB,Ryanair DAC,FR8400
3,AFG,FCO,IST,2024,01,25,2024-01-25 13:05:00,Fiumicino,Havalimani,Roma,...,Turkish Airlines,TK1865,NaN,NaN,NaN,N.D.,61+,AFG,Turkish Airlines,TK1865
4,ALB,BGY,MLE,2024,02,13,FEB 13 2024,Orio al Serio,Male International,Bergamo,...,Fly Dubai,FZ1571,SEGNALATO,NaN,NaN,Permesso di soggiorno,46-60,ALB,Fly Dubai,FZ1571


In [843]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 5095 entries, 0 to 5094
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NAZIONALITA            4979 non-null   str  
 1   AREOPORTO_ARRIVO       5095 non-null   str  
 2   AREOPORTO_PARTENZA     5095 non-null   str  
 3   ANNO_PARTENZA          5095 non-null   str  
 4   MESE_PARTENZA          5095 non-null   str  
 5   GIORNO_PARTENZA        5095 non-null   int64
 6   DATA_PARTENZA          5095 non-null   str  
 7   DESCR_AEREOPORTO_ARR   5095 non-null   str  
 8   DESCR_AEREOPORTO_PART  5095 non-null   str  
 9   CITTA_ARR              5095 non-null   str  
 10  CITTA_PARTENZA         5095 non-null   str  
 11  CODICE_PAESE_ARR       5095 non-null   str  
 12  CODICE_PAESE_PART      5095 non-null   str  
 13  PAESE_ARR              5095 non-null   str  
 14  PAESE_PART             5095 non-null   str  
 15  ZONA                   5095 non-null   str  
 16 

ANCHE IN QUESTO DATASET PER ORA HO TOLTO IL DROP DUPLICATES

In [844]:
# Normalize: lowercase and strip all string values
df2 = df2.map(lambda x: x.strip().lower() if isinstance(x, str) else x)

#print("Initial duplicates:", df2.duplicated().sum())
#df2 = df2.drop_duplicates()
#print("Duplicates after cleaning:", df2.duplicated().sum())
#print(f"Shape: {df2.shape}")

### NAZIONALITA

In [845]:
print(f"Unique values: {df2['NAZIONALITA'].nunique()}")
print(f"Null values: {df2['NAZIONALITA'].isnull().sum()}")
print()
print(df2['NAZIONALITA'].value_counts(dropna=False).to_string())

Unique values: 19
Null values: 116

NAZIONALITA
alb        4281
afg         386
NaN         116
ago          50
and          35
nd           34
-            31
?            28
n.d.         26
//           25
unknown      25
             24
are          19
zz            3
unk           3
xx            3
???           2
abw           2
aia           1
eu            1


In [846]:
# Replace placeholder values with NaN (keep valid ISO-3 codes)
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "unk", "zz", "none", "xx", "???"}

df2["NAZIONALITA"] = df2["NAZIONALITA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Null left: {df2['NAZIONALITA'].isnull().sum()}")
print(df2["NAZIONALITA"].value_counts(dropna=False).to_string())

Null left: 320
NAZIONALITA
alb    4281
afg     386
NaN     320
ago      50
and      35
are      19
abw       2
aia       1
eu        1


### Airport columns

In [847]:
print("--- AREOPORTO_ARRIVO ---")
print(f"Unique: {df2['AREOPORTO_ARRIVO'].nunique()}  |  Null: {df2['AREOPORTO_ARRIVO'].isnull().sum()}")
print(df2['AREOPORTO_ARRIVO'].value_counts(dropna=False).to_string())
print()
print("--- AREOPORTO_PARTENZA ---")
print(f"Unique: {df2['AREOPORTO_PARTENZA'].nunique()}  |  Null: {df2['AREOPORTO_PARTENZA'].isnull().sum()}")
print(df2['AREOPORTO_PARTENZA'].value_counts(dropna=False).to_string())

--- AREOPORTO_ARRIVO ---
Unique: 29  |  Null: 0
AREOPORTO_ARRIVO
mxp    1043
fco     889
bgy     680
blq     468
psa     283
vce     205
tsf     187
cta     158
trn     155
bri     154
cia     151
vrn     148
goa      95
nap      92
aoi      64
lin      55
peg      47
psr      43
flr      38
rmi      26
trs      25
bds      23
cag      20
pmo      17
suf      14
ciy      10
cuf       2
reg       2
pmf       1

--- AREOPORTO_PARTENZA ---
Unique: 177  |  Null: 0
AREOPORTO_PARTENZA
tia    2262
stn     507
lgw     267
saw     210
dxb     113
jfk     112
ist     109
lhr      88
man      88
ssh      84
ika      83
kbl      73
jed      71
ltn      55
mle      47
auh      38
bhx      34
skp      31
ewr      29
prn      29
rak      28
lad      27
brs      25
tgd      24
bkk      24
hkt      24
amm      21
ruh      19
mia      17
tun      16
rmf      16
shj      15
beg      15
cai      15
znz      14
yyz      14
mhd      14
rmo      14
isb      13
spx      13
cmn      13
lcy      12
doh      10


### ANNO_PARTENZA

In [848]:
print(f"Unique values: {df2['ANNO_PARTENZA'].nunique()}")
print(f"Null values: {df2['ANNO_PARTENZA'].isnull().sum()}")
print()
print(df2['ANNO_PARTENZA'].value_counts(dropna=False).to_string())

Unique values: 4
Null values: 0

ANNO_PARTENZA
2024         4695
2023          254
24             73
anno 2024      73


In [849]:
def normalizza_anno(val):
    if pd.isna(val): return np.nan
    val = str(val).strip()
    match = re.search(r"\b(20\d{2})\b", val)
    if match: return int(match.group(1))
    match = re.search(r"\b(\d{2})\b", val)
    if match: return int("20" + match.group(1))
    return np.nan

df2["ANNO_PARTENZA"] = df2["ANNO_PARTENZA"].apply(normalizza_anno)
print(df2["ANNO_PARTENZA"].value_counts(dropna=False).to_string())

ANNO_PARTENZA
2024    4841
2023     254


### MESE_PARTENZA

In [850]:
print(f"Unique values: {df2['MESE_PARTENZA'].nunique()}")
print(f"Null values: {df2['MESE_PARTENZA'].isnull().sum()}")
print()
print(df2['MESE_PARTENZA'].value_counts(dropna=False).sort_index().to_string())

Unique values: 5
Null values: 0

MESE_PARTENZA
01     2633
02     2307
12        1
feb      61
gen      93


In [851]:
mesi_map = {"gen": "01", "feb": "02"}
df2["MESE_PARTENZA"] = df2["MESE_PARTENZA"].replace(mesi_map)

print(df2["MESE_PARTENZA"].value_counts(dropna=False).sort_index().to_string())

MESE_PARTENZA
01    2726
02    2368
12       1


### GIORNO_PARTENZA

In [852]:
df2["GIORNO_PARTENZA"] = pd.to_numeric(df2["GIORNO_PARTENZA"], errors="coerce")

print(f"Unique values: {df2['GIORNO_PARTENZA'].nunique()}")
print(f"Null values: {df2['GIORNO_PARTENZA'].isnull().sum()}")
print(f"Min: {df2['GIORNO_PARTENZA'].min()}  |  Max: {df2['GIORNO_PARTENZA'].max()}")
print()

# Flag invalid days (outside 1-31)
invalid = df2[(df2["GIORNO_PARTENZA"] < 1) | (df2["GIORNO_PARTENZA"] > 31)]
print(f"Invalid day values: {len(invalid)}")
print(df2["GIORNO_PARTENZA"].value_counts(dropna=False).sort_index().to_string())

Unique values: 31
Null values: 0
Min: 1  |  Max: 31

Invalid day values: 0
GIORNO_PARTENZA
1     170
2     193
3     179
4     194
5     168
6     192
7     177
8     161
9     170
10    163
11    179
12    176
13    191
14    181
15    157
16    178
17    152
18    174
19    175
20    179
21    149
22    155
23    169
24    174
25    156
26    172
27    175
28    141
29    152
30     77
31     66


In [853]:
# Null out invalid day values
n_invalid = ((df2["GIORNO_PARTENZA"] < 1) | (df2["GIORNO_PARTENZA"] > 31)).sum()
df2.loc[(df2["GIORNO_PARTENZA"] < 1) | (df2["GIORNO_PARTENZA"] > 31), "GIORNO_PARTENZA"] = np.nan
df2["GIORNO_PARTENZA"] = df2["GIORNO_PARTENZA"].astype("Int64")
print(f"Nulled {n_invalid} invalid day(s). Null left: {df2['GIORNO_PARTENZA'].isnull().sum()}")

Nulled 0 invalid day(s). Null left: 0


### DATA_PARTENZA

In [854]:
print(f"Unique values: {df2['DATA_PARTENZA'].nunique()}")
print(f"Null values: {df2['DATA_PARTENZA'].isnull().sum()}")
print()
print(df2['DATA_PARTENZA'].value_counts(dropna=False).head(15).to_string())

Unique values: 3977
Null values: 0

DATA_PARTENZA
2024-02-11 16:55:00    7
2024-01-14 16:55:00    7
2024-01-21 16:55:00    6
2024-01-28 16:55:00    6
2024-01-10 05:35:00    6
2024-02-08 05:35:00    5
2024-02-18 16:55:00    5
feb 10 2024            5
24-02-24               5
24.01.2024             5
2024-01-03 08:55:00    5
gen 18 2024            5
2024-01-09 05:35:00    5
2024-02-13 05:35:00    5
2024-01-02 05:35:00    5


In [855]:
mesi_ita = {
    "GEN": "01", "FEB": "02", "MAR": "03", "APR": "04",
    "MAG": "05", "GIU": "06", "LUG": "07", "AGO": "08",
    "SET": "09", "OTT": "10", "NOV": "11", "DIC": "12"
}

def normalizza_data(val):
    val = str(val).strip()

    # "GEN 06 2024" → "2024-01-06 00:00:00"
    for ita, num in mesi_ita.items():
        if val.upper().startswith(ita + " "):
            parts = val.split(" ")
            return f"{parts[2]}-{num}-{parts[1].zfill(2)} 00:00:00"

    val = val.replace("T", " ")

    if re.match(r"\d{4}/\d{2}/\d{2}", val):
        val = val.replace("/", "-")
        if len(val) == 10:
            val += " 00:00:00"

    match = re.match(r"(\d{2})\.(\d{2})\.(\d{4})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    match = re.match(r"(\d{2})-(\d{2})-(\d{2})$", val)
    if match:
        return f"20{match.group(3)}-{match.group(2)}-{match.group(1)} 00:00:00"

    match = re.match(r"(\d{2})/(\d{2})/(\d{4})\s(\d{2}:\d{2}:\d{2})", val)
    if match:
        return f"{match.group(3)}-{match.group(2)}-{match.group(1)} {match.group(4)}"

    return val

df2["DATA_PARTENZA"] = df2["DATA_PARTENZA"].apply(normalizza_data)
df2["DATA_PARTENZA"] = pd.to_datetime(df2["DATA_PARTENZA"], errors="coerce")

# Recover NaT using ANNO + MESE + GIORNO (full date available in df2)
nat_mask = df2["DATA_PARTENZA"].isnull()
df2.loc[nat_mask, "DATA_PARTENZA"] = pd.to_datetime(
    df2.loc[nat_mask, "ANNO_PARTENZA"].astype(str) + "-" +
    df2.loc[nat_mask, "MESE_PARTENZA"].astype(str).str.zfill(2) + "-" +
    df2.loc[nat_mask, "GIORNO_PARTENZA"].astype(str).str.zfill(2),
    errors="coerce"
)

print(f"NaT left: {df2['DATA_PARTENZA'].isnull().sum()}")
print(f"Range: {df2['DATA_PARTENZA'].min()} → {df2['DATA_PARTENZA'].max()}")

NaT left: 0
Range: 2023-01-14 00:00:00 → 2024-02-29 21:55:00


### Airport descriptions (DESCR_AEREOPORTO_ARR / DESCR_AEREOPORTO_PART)

In [856]:
print("--- DESCR_AEREOPORTO_ARR ---")
print(f"Unique: {df2['DESCR_AEREOPORTO_ARR'].nunique()}  |  Null: {df2['DESCR_AEREOPORTO_ARR'].isnull().sum()}")
print()
print("--- DESCR_AEREOPORTO_PART ---")
print(f"Unique: {df2['DESCR_AEREOPORTO_PART'].nunique()}  |  Null: {df2['DESCR_AEREOPORTO_PART'].isnull().sum()}")
print()
print("Both will be dropped — redundant with IATA codes.")

--- DESCR_AEREOPORTO_ARR ---
Unique: 29  |  Null: 0

--- DESCR_AEREOPORTO_PART ---
Unique: 176  |  Null: 0

Both will be dropped — redundant with IATA codes.


### CITTA_ARR and CITTA_PARTENZA

In [857]:
print("--- CITTA_ARR ---")
print(f"Unique: {df2['CITTA_ARR'].nunique()}  |  Null: {df2['CITTA_ARR'].isnull().sum()}")
print(df2['CITTA_ARR'].value_counts(dropna=False).to_string())
print()
print("--- CITTA_PARTENZA ---")
print(f"Unique: {df2['CITTA_PARTENZA'].nunique()}  |  Null: {df2['CITTA_PARTENZA'].isnull().sum()}")
print(df2['CITTA_PARTENZA'].value_counts(dropna=False).to_string())

--- CITTA_ARR ---
Unique: 27  |  Null: 0
CITTA_ARR
milano             1098
roma               1040
bergamo             680
bologna             468
pisa                283
venezia             205
treviso             187
catania             158
torino              155
bari                154
verona              148
genova               95
napoli               92
ancona               64
perugia              47
pescara              43
firenze              38
rimini               26
trieste              25
brindisi             23
cagliari             20
palermo              17
lamezia terme        14
comiso               10
cuneo                 2
reggio calabria       2
parma                 1

--- CITTA_PARTENZA ---
Unique: 165  |  Null: 0
CITTA_PARTENZA
tirana               2262
londra                929
istanbul              319
dubai                 115
new york              112
manchester             88
sharm el sheikh        84
tehran                 83
kabul                  73
jedd

In [858]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "anu", "none"}

df2["CITTA_PARTENZA"] = df2["CITTA_PARTENZA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df2['CITTA_PARTENZA'].isnull().sum()}")

# Recover nulls via IATA → city lookup (same dictionary as df1)
iata_city = {
    "tia": "tirana",   "stn": "londra",    "lgw": "londra",   "lhr": "londra",
    "lcy": "londra",   "ltn": "londra",    "bqh": "londra",   "fab": "londra",
    "ist": "istanbul", "dxb": "dubai",     "cai": "il cairo", "saw": "istanbul",
    "cmn": "casablanca","doh": "doha",     "rak": "marrakech","jfk": "new york",
    "ssh": "sharm el-sheikh","tun": "tunisi","beg": "belgrado","auh": "abu dhabi",
    "ewr": "new york", "jed": "jeddah",    "edi": "edinburgo","gru": "san paolo",
    "eze": "buenos aires","add": "addis abeba","mex": "citta del messico",
    "pek": "pechino",  "rmo": "chisinau",  "bhx": "birmingham","pvg": "shanghai",
    "hkg": "hong kong","mct": "muscat",    "mle": "male",     "rba": "rabat",
    "evn": "yerevan",  "tbs": "tbilisi",   "ema": "east midlands","ruh": "riad",
    "shj": "sharjah",  "gla": "glasgow",   "icn": "seul",     "rmf": "marsa alam",
    "tng": "tangeri",  "sid": "praia",     "spx": "cairo",    "ika": "teheran",
    "prn": "pristina", "mba": "mombasa",   "szx": "shenzhen", "mia": "miami",
    "tpe": "taipei",   "sin": "singapore", "tlv": "tel aviv", "amm": "amman",
    "brs": "bristol",  "man": "manchester","anu": "saint john's","ncl": "newcastle",
    "del": "nuova delhi","atl": "atlanta", "kwi": "kuwait",   "dfw": "dallas",
    "iad": "washington","yul": "montreal", "yyz": "toronto",  "hnd": "tokyo",
    "bey": "beirut",   "alg": "algeri",    "kiv": "chisinau", "gyd": "baku",
    "lpl": "liverpool","skp": "skopje",    "tgd": "podgorica","phl": "filadelfia",
    "fez": "fez",      "gig": "rio de janeiro","atq": "amritsar","znz": "zanzibar",
    "nkg": "nanchino", "aga": "agadir",    "mji": "misurata", "dmm": "dammam",
    "ckg": "chongqing","bfs": "belfast",   "bos": "boston",   "lxr": "luxor",
    "can": "guangzhou","wnz": "wenzhou",   "hgh": "hangzhou", "bah": "manama",
    "dss": "dakar",    "kut": "kutaisi",   "hrg": "hurghada", "oak": "oakland",
    "lax": "los angeles","oxf": "oxford",  "lba": "leeds",    "ala": "almaty",
    "mbj": "montego bay","cun": "cancun",  "mru": "port louis","tas": "tashkent",
    "cgo": "zhengzhou","tfu": "chengdu",  "nht": "londra",
}

null_mask = df2["CITTA_PARTENZA"].isnull()
df2.loc[null_mask, "CITTA_PARTENZA"] = (
    df2.loc[null_mask, "AREOPORTO_PARTENZA"].str.strip().str.lower().map(iata_city)
)

# Fallback: data-driven lookup from other rows
iata_city_from_data = (
    df2[df2["CITTA_PARTENZA"].notna()]
    .groupby("AREOPORTO_PARTENZA")["CITTA_PARTENZA"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df2["CITTA_PARTENZA"].isnull()
df2.loc[null_mask, "CITTA_PARTENZA"] = (
    df2.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_city_from_data)
)

print(f"Null left: {df2['CITTA_PARTENZA'].isnull().sum()}")
print(f"Unique values: {df2['CITTA_PARTENZA'].nunique()}")

Nulls after placeholder cleanup: 0
Null left: 0
Unique values: 165


### Country columns

In [859]:
print("--- CODICE_PAESE_ARR ---")
print(f"Unique: {df2['CODICE_PAESE_ARR'].nunique()}  |  Null: {df2['CODICE_PAESE_ARR'].isnull().sum()}")
print(df2['CODICE_PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- CODICE_PAESE_PART ---")
print(f"Unique: {df2['CODICE_PAESE_PART'].nunique()}  |  Null: {df2['CODICE_PAESE_PART'].isnull().sum()}")
print(df2['CODICE_PAESE_PART'].value_counts(dropna=False).head(20).to_string())

--- CODICE_PAESE_ARR ---
Unique: 2  |  Null: 0
CODICE_PAESE_ARR
ita    4836
it      259

--- CODICE_PAESE_PART ---
Unique: 82  |  Null: 0
CODICE_PAESE_PART
alb    2154
gbr    1051
tur     309
usa     204
are     158
egy     125
al      108
irn     100
sau      97
afg      73
gb       54
tha      48
mdv      47
mar      40
mkd      31
rks      29
ago      27
chn      25
tr       24
mne      24


In [860]:
# CODICE_PAESE_ARR: always Italy — overwrite all variants with "ita"
n_wrong = (df2["CODICE_PAESE_ARR"] != "ita").sum()
print(f"Rows with non-'ita' value: {n_wrong}")
df2["CODICE_PAESE_ARR"] = "ita"

Rows with non-'ita' value: 259


In [861]:
print("--- PAESE_ARR ---")
print(f"Unique: {df2['PAESE_ARR'].nunique()}  |  Null: {df2['PAESE_ARR'].isnull().sum()}")
print(df2['PAESE_ARR'].value_counts(dropna=False).to_string())
print()
print("--- PAESE_PART ---")
print(f"Unique: {df2['PAESE_PART'].nunique()}  |  Null: {df2['PAESE_PART'].isnull().sum()}")
print(df2['PAESE_PART'].value_counts(dropna=False).head(20).to_string())

--- PAESE_ARR ---
Unique: 1  |  Null: 0
PAESE_ARR
italia    5095

--- PAESE_PART ---
Unique: 76  |  Null: 0
PAESE_PART
albania                2262
regno unito            1105
turchia                 333
stati uniti             204
emirati arabi uniti     168
egitto                  136
iran                    100
arabia saudita           97
afghanistan              73
thailandia               48
maldive                  47
marocco                  43
macedonia                31
cossovo                  29
angola                   27
cina                     25
montenegro               24
pakistan                 23
canada                   22
giordania                21


In [862]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "anu", "none"}

df2["PAESE_PART"] = df2["PAESE_PART"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

print(f"Nulls after placeholder cleanup: {df2['PAESE_PART'].isnull().sum()}")

codice_paese_map = {
    "alb": "albania",          "gbr": "regno unito",      "tur": "turchia",
    "are": "emirati arabi",    "egy": "egitto",            "mar": "marocco",
    "qat": "qatar",            "usa": "stati uniti",       "tun": "tunisia",
    "srb": "serbia",           "sau": "arabia saudita",    "bra": "brasile",
    "arg": "argentina",        "eth": "etiopia",           "mex": "messico",
    "chn": "cina",             "mda": "moldavia",          "hkg": "hong kong",
    "omn": "oman",             "mdv": "maldive",           "arm": "armenia",
    "geo": "georgia",          "kor": "corea del sud",     "cpv": "capo verde",
    "irn": "iran",             "xkx": "kosovo",            "ken": "kenya",
    "tza": "tanzania",         "twn": "taiwan",            "sgp": "singapore",
    "isr": "israele",          "jor": "giordania",         "ind": "india",
    "kwt": "kuwait",           "can": "canada",            "jpn": "giappone",
    "lbn": "libano",           "dza": "algeria",           "aze": "azerbaigian",
    "mkd": "macedonia",        "mne": "montenegro",        "atg": "antigua",
    "sen": "senegal",          "bhr": "bahrein",           "lby": "libia",
    "jam": "giamaica",         "mus": "mauritius",         "uzb": "uzbekistan",
    "sle": "sierra leone",     "kaz": "kazakistan",        "pak": "pakistan",
    "afg": "afghanistan",      "tha": "thailandia",        "npl": "nepal",
    "phl": "filippine",        "lka": "sri lanka",         "bgd": "bangladesh",
    "nga": "nigeria",          "cmr": "camerun",           "gha": "ghana",
    "civ": "costa d'avorio",  "mli": "mali",              "gin": "guinea",
}

null_mask = df2["PAESE_PART"].isnull()
df2.loc[null_mask, "PAESE_PART"] = (
    df2.loc[null_mask, "CODICE_PAESE_PART"].str.strip().str.lower().map(codice_paese_map)
)

# Fallback: data-driven lookup
iata_paese_from_data = (
    df2[df2["PAESE_PART"].notna()]
    .groupby("AREOPORTO_PARTENZA")["PAESE_PART"]
    .agg(lambda x: x.mode()[0])
    .to_dict()
)
null_mask = df2["PAESE_PART"].isnull()
df2.loc[null_mask, "PAESE_PART"] = (
    df2.loc[null_mask, "AREOPORTO_PARTENZA"].map(iata_paese_from_data)
)

print(f"Null left PAESE_PART: {df2['PAESE_PART'].isnull().sum()}")
print(df2["PAESE_PART"].value_counts(dropna=False).head(20).to_string())

Nulls after placeholder cleanup: 0
Null left PAESE_PART: 0
PAESE_PART
albania                2262
regno unito            1105
turchia                 333
stati uniti             204
emirati arabi uniti     168
egitto                  136
iran                    100
arabia saudita           97
afghanistan              73
thailandia               48
maldive                  47
marocco                  43
macedonia                31
cossovo                  29
angola                   27
cina                     25
montenegro               24
pakistan                 23
canada                   22
giordania                21


### ZONA

In [863]:
print(f"Unique values: {df2['ZONA'].nunique()}")
print(f"Null values: {df2['ZONA'].isnull().sum()}")
print()
print(df2['ZONA'].value_counts(dropna=False).sort_index().to_string())

Unique values: 13
Null values: 0

ZONA
-1       3
0        4
1      252
10       1
2     1774
4      564
5     1106
6      107
7      184
8      878
9      220
99       1
??       1


In [864]:
# -1 is not a valid zone — treat as missing before casting
df2["ZONA"] = df2["ZONA"].replace("-1", np.nan)
df2["ZONA"] = pd.to_numeric(df2["ZONA"], errors="coerce")
df2.loc[df2["ZONA"] == -1, "ZONA"] = np.nan
df2["ZONA"] = df2["ZONA"].astype(pd.Int64Dtype())

print(f"Null left (were -1): {df2['ZONA'].isnull().sum()}")
print(f"dtype: {df2['ZONA'].dtype}")
print(df2["ZONA"].value_counts(dropna=False).sort_index().to_string())

Null left (were -1): 4
dtype: Int64
ZONA
0          4
1        252
2       1774
4        564
5       1106
6        107
7        184
8        878
9        220
10         1
99         1
<NA>       4


### ENTRATI, INVESTIGATI, ALLARMATI

In [865]:
for col in ["ENTRATI", "INVESTIGATI", "ALLARMATI"]:
    print(f"--- {col} ---")
    print(f"Unique: {df2[col].nunique()}  |  Null: {df2[col].isnull().sum()}")
    print(df2[col].value_counts(dropna=False).head(10).to_string())
    print()

--- ENTRATI ---
Unique: 251  |  Null: 0
ENTRATI
1       1894
2        515
3        187
4         97
5         63
n.d.      45
?         40
6         27
91        27
82        26

--- INVESTIGATI ---
Unique: 251  |  Null: 0
INVESTIGATI
1       1708
2        493
0        256
3        199
4        122
5         57
n.d.      51
?         33
6         29
91        27

--- ALLARMATI ---
Unique: 146  |  Null: 0
ALLARMATI
0     2096
1      675
2      154
4      119
3      112
6      107
10     103
7      101
11      99
5       99



In [866]:
# Cast to nullable integer — non-numeric placeholders become NaN
for col in ["ENTRATI", "INVESTIGATI", "ALLARMATI"]:
    df2[col] = pd.to_numeric(df2[col], errors="coerce").astype("Float64").astype("Int64")

# Null out negative values (impossible counts)
for col in ["ENTRATI", "INVESTIGATI", "ALLARMATI"]:
    n_neg = (df2[col] < 0).sum()
    df2.loc[df2[col] < 0, col] = pd.NA
    print(f"{col}: Null={df2[col].isnull().sum()}  Min={df2[col].min()}  Max={df2[col].max()}  (nulled {n_neg} negative(s))")

ENTRATI: Null=206  Min=0  Max=10000  (nulled 3 negative(s))
INVESTIGATI: Null=206  Min=0  Max=9999  (nulled 3 negative(s))
ALLARMATI: Null=206  Min=0  Max=5000  (nulled 3 negative(s))


In [867]:
df2 = df2.dropna(subset=['ENTRATI', 'INVESTIGATI', 'ALLARMATI'])
print(df2.shape)

(4883, 33)


In [868]:
# INVESTIGATI > ENTRATI
mask = (df2['INVESTIGATI'] > df2['ENTRATI']) & ((df2['INVESTIGATI'] - df2['ENTRATI']) <= 5)
df2.loc[mask, 'INVESTIGATI'] = df2.loc[mask, 'ENTRATI']
df2 = df2[~(df2['INVESTIGATI'] > df2['ENTRATI'])]

# ALLARMATI > INVESTIGATI
mask = (df2['ALLARMATI'] > df2['INVESTIGATI']) & ((df2['ALLARMATI'] - df2['INVESTIGATI']) <= 5)
df2.loc[mask, 'ALLARMATI'] = df2.loc[mask, 'INVESTIGATI']
df2 = df2[~(df2['ALLARMATI'] > df2['INVESTIGATI'])]

print(df2.shape)  # atteso circa 4818

(4876, 33)


### TIPO_DOCUMENTO

In [869]:
print(f"Unique values: {df2['TIPO_DOCUMENTO'].nunique()}")
print(f"Null values: {df2['TIPO_DOCUMENTO'].isnull().sum()}")
print()
print(df2['TIPO_DOCUMENTO'].value_counts(dropna=False).to_string())

Unique values: 11
Null values: 60

TIPO_DOCUMENTO
n.d.                     1546
visto                     829
permesso di soggiorno     794
passaporto                780
carta d'identità          747
NaN                        60
unknown                    29
?                          28
//                         21
nd                         16
                           14
-                          12


In [870]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none"}

df2["TIPO_DOCUMENTO"] = df2["TIPO_DOCUMENTO"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

# Recover nulls from duplicate column "Tipo Documento"
null_mask = df2["TIPO_DOCUMENTO"].isnull()
recovered = df2.loc[null_mask, "Tipo Documento"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else str(x).strip().lower()
)
df2.loc[null_mask, "TIPO_DOCUMENTO"] = recovered

print(f"Null left: {df2['TIPO_DOCUMENTO'].isnull().sum()}")
print(df2["TIPO_DOCUMENTO"].value_counts(dropna=False).to_string())

Null left: 1597
TIPO_DOCUMENTO
NaN                      1597
visto                     856
permesso di soggiorno     831
passaporto                813
carta d'identità          779


### GENERE

In [871]:
print(f"Unique values: {df2['GENERE'].nunique()}")
print(f"Null values: {df2['GENERE'].isnull().sum()}")
print()
print(df2['GENERE'].value_counts(dropna=False).to_string())

Unique values: 18
Null values: 40

GENERE
m          2046
f          2043
n.d.        484
female       56
NaN          40
male         31
femmina      28
maschio      24
2            21
//           17
             16
?            16
nd           14
1            14
-            13
unknown       7
x             3
n/b           2
unkn          1


In [872]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none"}

genere_map = {
    "f": "f", "female": "f", "femmina": "f", "2": "f",
    "m": "m", "male": "m",   "maschio": "m", "1": "m",
}

df2["GENERE"] = df2["GENERE"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
    else genere_map.get(str(x).strip(), np.nan)
)

print(f"Null left: {df2['GENERE'].isnull().sum()}")
print(df2["GENERE"].value_counts(dropna=False).to_string())

Null left: 613
GENERE
f      2148
m      2115
NaN     613


### FASCIA_ETA

In [873]:
print(f"Unique values: {df2['FASCIA_ETA'].nunique()}")
print(f"Null values: {df2['FASCIA_ETA'].isnull().sum()}")
print()
print(df2['FASCIA_ETA'].value_counts(dropna=False).to_string())

Unique values: 11
Null values: 0

FASCIA_ETA
46-60     908
18-30     883
31-45     873
0-17      862
61+       847
n.d.      496
n/c         2
-5          2
minore      1
adulto      1
101+        1


In [874]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none", "n/c", "adulto"}

fascia_map = {
    "minore": "0-17",   # minore = under 18
}

df2["FASCIA_ETA"] = df2["FASCIA_ETA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
    else fascia_map.get(str(x).strip(), str(x).strip())
)

# Null out clearly invalid values (negative ages)
df2.loc[df2["FASCIA_ETA"].str.startswith("-", na=False), "FASCIA_ETA"] = np.nan

print(f"Null left: {df2['FASCIA_ETA'].isnull().sum()}")
print(df2["FASCIA_ETA"].value_counts(dropna=False).to_string())

Null left: 501
FASCIA_ETA
46-60    908
18-30    883
31-45    873
0-17     863
61+      847
NaN      501
101+       1


### FLAG_TRANSITO

In [875]:
print(f"Unique values: {df2['FLAG_TRANSITO'].nunique()}")
print(f"Null values: {df2['FLAG_TRANSITO'].isnull().sum()}")
print()
print(df2['FLAG_TRANSITO'].value_counts(dropna=False).to_string())

# Replace n/c with NaN
df2["FLAG_TRANSITO"] = df2["FLAG_TRANSITO"].replace("n/c", np.nan)
print(f"\nNull after n/c cleanup: {df2['FLAG_TRANSITO'].isnull().sum()}")

Unique values: 5
Null values: 0

FLAG_TRANSITO
singola tratta    4864
multitratta          5
transito             3
tripla tratta        3
n/c                  1

Null after n/c cleanup: 1


### COMPAGNIA_AEREA

In [876]:
print(f"Unique values: {df2['COMPAGNIA_AEREA'].nunique()}")
print(f"Null values: {df2['COMPAGNIA_AEREA'].isnull().sum()}")
print()
print(df2['COMPAGNIA_AEREA'].value_counts(dropna=False).to_string())

Unique values: 77
Null values: 82

COMPAGNIA_AEREA
wizz air malta             1647
ryanair dac                1021
turkish airlines            255
ita airways                 241
pegasus airlines            147
easyjet                     133
emirates                    125
british airways             103
fly dubai                    88
NaN                          82
air albania                  81
easyjet europe               80
neos s.p.a.                  70
qatar airways                68
etihad airways               52
wizz air hungary             38
albawings                    38
delta air lines              34
united airlines              33
air serbia                   29
-                            29
ethiopian airlines           29
                             28
american airlines            26
unknown                      24
?                            23
//                           21
n.d.                         21
vueling airlines             21
air arabia           

In [877]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null",
                    "none", "??", "compagnia x", "charter"}

df2["COMPAGNIA_AEREA"] = df2["COMPAGNIA_AEREA"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

# Recover nulls from duplicate column "compagnia%aerea"
null_mask = df2["COMPAGNIA_AEREA"].isnull()
df2.loc[null_mask, "COMPAGNIA_AEREA"] = (
    df2.loc[null_mask, "compagnia%aerea"]
    .apply(lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
           else str(x).strip().lower())
)

print(f"Null left: {df2['COMPAGNIA_AEREA'].isnull().sum()}")
print(df2["COMPAGNIA_AEREA"].value_counts(dropna=False).head(15).to_string())

Null left: 0
COMPAGNIA_AEREA
wizz air malta      1740
ryanair dac         1085
turkish airlines     266
ita airways          252
pegasus airlines     154
easyjet              139
emirates             133
british airways      109
fly dubai             92
easyjet europe        85
air albania           83
qatar airways         74
neos s.p.a.           72
etihad airways        53
albawings             40


### NUMERO_VOLO

In [878]:
PLACEHOLDER_NULL = {"n.d.", "?", "", "//", "-", "unknown", "nd", "n/a", "null", "none"}

df2["NUMERO_VOLO"] = df2["NUMERO_VOLO"].apply(
    lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL else x
)

# Recover nulls from duplicate column "num volo"
null_mask = df2["NUMERO_VOLO"].isnull()
df2.loc[null_mask, "NUMERO_VOLO"] = (
    df2.loc[null_mask, "num volo"]
    .apply(lambda x: np.nan if pd.isna(x) or str(x).strip() in PLACEHOLDER_NULL
           else str(x).strip().lower())
)

print(f"Null left: {df2['NUMERO_VOLO'].isnull().sum()}")

# Flag flight numbers with inconsistent routes (data quality check)
consistency = (
    df2[df2["NUMERO_VOLO"].notna()]
    .groupby("NUMERO_VOLO")
    .agg(arr_unique=("AREOPORTO_ARRIVO", "nunique"),
         part_unique=("AREOPORTO_PARTENZA", "nunique"))
)
inconsistent = consistency[(consistency["arr_unique"] > 1) | (consistency["part_unique"] > 1)]
print(f"\nFlight numbers with inconsistent routes: {len(inconsistent)} (flagged, not modified)")
print(inconsistent.head(10).to_string())

Null left: 0

Flight numbers with inconsistent routes: 119 (flagged, not modified)
             arr_unique  part_unique
NUMERO_VOLO                         
3u3895                1            3
5f0295                1            2
aa0198                1            6
aa0240                1            2
aa0718                1            2
ac0890                1            3
ac0892                1            4
ac0894                1            4
ah2026                1            2
at0940                2            3


### ESITO_CONTROLLO

In [879]:
print(f"Unique values: {df2['ESITO_CONTROLLO'].nunique()}")
print(f"Null values: {df2['ESITO_CONTROLLO'].isnull().sum()}  ({df2['ESITO_CONTROLLO'].isnull().mean()*100:.1f}%)")
print()
print(df2['ESITO_CONTROLLO'].value_counts(dropna=False).to_string())

Unique values: 5
Null values: 1233  (25.3%)

ESITO_CONTROLLO
NaN          1233
segnalato     770
in attesa     749
respinto      742
fermato       698
ok            684


### note_operatore and codice_rischio

In [880]:
print(f"note_operatore:  {df2['note_operatore'].isnull().sum()} nulls  ({df2['note_operatore'].isnull().mean()*100:.1f}%)")
print(df2['note_operatore'].value_counts(dropna=False).head(10).to_string())
print()
print(f"codice_rischio:  {df2['codice_rischio'].isnull().sum()} nulls  ({df2['codice_rischio'].isnull().mean()*100:.1f}%)")
print(df2['codice_rischio'].value_counts(dropna=False).head(10).to_string())

note_operatore:  4819 nulls  (98.8%)
note_operatore
NaN                     4819
verifica richiesta        17
alert manuale             15
segnalazione esterna      14
passeggero noto           11

codice_rischio:  4838 nulls  (99.2%)
codice_rischio
NaN    4838
r3       16
r2       13
r1        9


## Merging the two datasets

### Cross-check duplicate columns

In [881]:
def norm_str(s):
    if pd.isna(s): return ""
    s = str(s).strip().lower().rstrip(".")
    return "" if s in {"nan", "none", "n/a", "nd", "n.d.", "<na>"} else s

dup_checks = [
    ("Tipo Documento",  "TIPO_DOCUMENTO"),
    ("FASCIA ETA",      "FASCIA_ETA"),
    ("3nazionalita",    "NAZIONALITA"),
    ("compagnia%aerea", "COMPAGNIA_AEREA"),
    ("num volo",        "NUMERO_VOLO"),
]

for dup, orig in dup_checks:
    nd = df2[dup].map(norm_str)
    no = df2[orig].map(norm_str)
    n_mismatch = (nd != no).sum()
    print(f"'{dup}' ~= '{orig}':  {n_mismatch} mismatches out of {len(df2)}")
    if 0 < n_mismatch <= 10:
        print(df2.loc[nd != no, [dup, orig]].to_string())
    elif n_mismatch > 10:
        print("  sample differences:")
        print(df2.loc[nd != no, [dup, orig]].head(5).to_string())

'Tipo Documento' ~= 'TIPO_DOCUMENTO':  1597 mismatches out of 4876
  sample differences:
   Tipo Documento TIPO_DOCUMENTO
2            n.d.            NaN
3            n.d.            NaN
8            n.d.            NaN
13           n.d.            NaN
15           n.d.            NaN
'FASCIA ETA' ~= 'FASCIA_ETA':  502 mismatches out of 4876
  sample differences:
   FASCIA ETA FASCIA_ETA
0        n.d.        NaN
8        n.d.        NaN
14       n.d.        NaN
20       n.d.        NaN
26       n.d.        NaN
'3nazionalita' ~= 'NAZIONALITA':  303 mismatches out of 4876
  sample differences:
   3nazionalita NAZIONALITA
1           alb         NaN
14          alb         NaN
32          alb         NaN
33          afg         NaN
39          alb         NaN
'compagnia%aerea' ~= 'COMPAGNIA_AEREA':  0 mismatches out of 4876
'num volo' ~= 'NUMERO_VOLO':  0 mismatches out of 4876


In [882]:
cols_to_drop = [
    # Duplicate columns
    "Tipo Documento", "FASCIA ETA", "3nazionalita", "compagnia%aerea", "num volo",
    # Airport descriptions: redundant with IATA codes
    "DESCR_AEREOPORTO_ARR", "DESCR_AEREOPORTO_PART",
    # Arrival country: always "italia"/"ita" — zero variance
    "CODICE_PAESE_ARR", "PAESE_ARR",
    # Departure country: keep PAESE_PART, drop ISO-3 code
    "CODICE_PAESE_PART",
    # Date: subsumed by DATA_PARTENZA (NaT rows already recovered above)
    "ANNO_PARTENZA", "MESE_PARTENZA", "GIORNO_PARTENZA",
]
df2.drop(columns=cols_to_drop, inplace=True)

print(f"Remaining columns ({df2.shape[1]}):")
print(df2.columns.tolist())

Remaining columns (20):
['NAZIONALITA', 'AREOPORTO_ARRIVO', 'AREOPORTO_PARTENZA', 'DATA_PARTENZA', 'CITTA_ARR', 'CITTA_PARTENZA', 'PAESE_PART', 'ZONA', 'ENTRATI', 'INVESTIGATI', 'ALLARMATI', 'TIPO_DOCUMENTO', 'GENERE', 'FASCIA_ETA', 'FLAG_TRANSITO', 'COMPAGNIA_AEREA', 'NUMERO_VOLO', 'ESITO_CONTROLLO', 'note_operatore', 'codice_rischio']


In [883]:
key = ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO', 'DATA_PARTENZA', 'NAZIONALITA', 'GENERE', 'FASCIA_ETA', 'NUMERO_VOLO']

df2 = df2.groupby(key, dropna=False).agg(
    ENTRATI=('ENTRATI', 'max'),
    INVESTIGATI=('INVESTIGATI', 'max'),
    ALLARMATI=('ALLARMATI', 'max'),
    CITTA_ARR=('CITTA_ARR', 'first'),
    CITTA_PARTENZA=('CITTA_PARTENZA', 'first'),
    PAESE_PART=('PAESE_PART', 'first'),
    ZONA=('ZONA', 'first'),
    TIPO_DOCUMENTO=('TIPO_DOCUMENTO', 'first'),
    FLAG_TRANSITO=('FLAG_TRANSITO', 'first'),
    COMPAGNIA_AEREA=('COMPAGNIA_AEREA', 'first'),
    ESITO_CONTROLLO=('ESITO_CONTROLLO', 'first'),
    note_operatore=('note_operatore', 'first'),
    codice_rischio=('codice_rischio', 'first')
).reset_index()

print(df2.shape)  # atteso circa 4784

(4784, 20)


In [884]:
# Pivot su OCCORRENZE
df1_pivot = df1.pivot_table(
    index=['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO', 'DATA_PARTENZA'],
    columns='OCCORRENZE',
    values='TOT',
    aggfunc='sum'
).reset_index()

df1_pivot.columns.name = None
df1_pivot.columns = [
    c if c in ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO', 'DATA_PARTENZA']
    else f'tot_{c.replace(" ", "_")}'
    for c in df1_pivot.columns
]

# Riempi NA con 0
cols_occorrenze = [c for c in df1_pivot.columns if c.startswith('tot_')]
df1_pivot[cols_occorrenze] = df1_pivot[cols_occorrenze].fillna(0)

# Aggiungi colonne descrittive
df1_desc = df1.groupby(
    ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO', 'DATA_PARTENZA']
).agg(
    CITTA_ARR=('CITTA_ARR', 'first'),
    CITTA_PARTENZA=('CITTA_PARTENZA', 'first'),
    PAESE_PART=('PAESE_PART', 'first'),
    ZONA=('ZONA', 'first'),
    MOTIVO_ALLARME=('MOTIVO_ALLARME', lambda x: x.mode()[0] if x.notna().any() else np.nan),
    note_operatore=('note_operatore', 'first'),
    flag_rischio=('flag_rischio', 'first')
).reset_index()

df1 = df1_pivot.merge(
    df1_desc,
    on=['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO', 'DATA_PARTENZA'],
    how='left'
)

print(f'df1 shape: {df1.shape}')
print(f'Chiave unica: {df1.duplicated(subset=["AREOPORTO_PARTENZA","AREOPORTO_ARRIVO","DATA_PARTENZA"]).sum()} duplicati')

df1 shape: (4334, 24)
Chiave unica: 0 duplicati


In [885]:
cols_occorrenze = [c for c in df1.columns if c.startswith('tot_')]

df1 = df1.groupby(
    ['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO']
).agg(
    **{col: (col, 'sum') for col in cols_occorrenze},
    CITTA_ARR=('CITTA_ARR', 'first'),
    CITTA_PARTENZA=('CITTA_PARTENZA', 'first'),
    PAESE_PART=('PAESE_PART', 'first'),
    ZONA=('ZONA', 'first'),
    MOTIVO_ALLARME=('MOTIVO_ALLARME', lambda x: x.mode()[0] if x.notna().any() else np.nan)
).reset_index()

print(f'df1 shape: {df1.shape}')

df1 shape: (366, 21)


In [886]:
df2 = df2.groupby(['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO']).apply(lambda g: pd.Series({
    # Contatori base
    'tot_entrati': g['ENTRATI'].sum(),
    'tot_investigati': g['INVESTIGATI'].sum(),
    'tot_allarmati': g['ALLARMATI'].sum(),
    'n_record': len(g),
    # Tasso allarme per rotta
    'tasso_allarme': g['ALLARMATI'].sum() / g['INVESTIGATI'].sum() if g['INVESTIGATI'].sum() > 0 else np.nan,
    # Tasso allarme per nazionalità
    'alert_rate_alb': g[g['NAZIONALITA']=='alb']['ALLARMATI'].sum() / g[g['NAZIONALITA']=='alb']['INVESTIGATI'].sum() if g[g['NAZIONALITA']=='alb']['INVESTIGATI'].sum() > 0 else np.nan,
    'alert_rate_afg': g[g['NAZIONALITA']=='afg']['ALLARMATI'].sum() / g[g['NAZIONALITA']=='afg']['INVESTIGATI'].sum() if g[g['NAZIONALITA']=='afg']['INVESTIGATI'].sum() > 0 else np.nan,
    'pct_naz_alb': (g['NAZIONALITA']=='alb').mean(),
    'pct_naz_afg': (g['NAZIONALITA']=='afg').mean(),
    # Tasso allarme per tipo documento
    'alert_rate_visto': g[g['TIPO_DOCUMENTO']=='visto']['ALLARMATI'].sum() / g[g['TIPO_DOCUMENTO']=='visto']['INVESTIGATI'].sum() if g[g['TIPO_DOCUMENTO']=='visto']['INVESTIGATI'].sum() > 0 else np.nan,
    'alert_rate_passaporto': g[g['TIPO_DOCUMENTO']=='passaporto']['ALLARMATI'].sum() / g[g['TIPO_DOCUMENTO']=='passaporto']['INVESTIGATI'].sum() if g[g['TIPO_DOCUMENTO']=='passaporto']['INVESTIGATI'].sum() > 0 else np.nan,
    'alert_rate_permesso': g[g['TIPO_DOCUMENTO']=='permesso di soggiorno']['ALLARMATI'].sum() / g[g['TIPO_DOCUMENTO']=='permesso di soggiorno']['INVESTIGATI'].sum() if g[g['TIPO_DOCUMENTO']=='permesso di soggiorno']['INVESTIGATI'].sum() > 0 else np.nan,
    'alert_rate_carta': g[g['TIPO_DOCUMENTO']=="carta d'identità"]['ALLARMATI'].sum() / g[g['TIPO_DOCUMENTO']=="carta d'identità"]['INVESTIGATI'].sum() if g[g['TIPO_DOCUMENTO']=="carta d'identità"]['INVESTIGATI'].sum() > 0 else np.nan,
    # Esito controllo
    'pct_segnalato': (g['ESITO_CONTROLLO']=='segnalato').sum() / g['ESITO_CONTROLLO'].notna().sum() if g['ESITO_CONTROLLO'].notna().sum() > 0 else np.nan,
    'pct_respinto': (g['ESITO_CONTROLLO']=='respinto').sum() / g['ESITO_CONTROLLO'].notna().sum() if g['ESITO_CONTROLLO'].notna().sum() > 0 else np.nan,
    'pct_fermato': (g['ESITO_CONTROLLO']=='fermato').sum() / g['ESITO_CONTROLLO'].notna().sum() if g['ESITO_CONTROLLO'].notna().sum() > 0 else np.nan,
    'pct_ok': (g['ESITO_CONTROLLO']=='ok').sum() / g['ESITO_CONTROLLO'].notna().sum() if g['ESITO_CONTROLLO'].notna().sum() > 0 else np.nan,
})).reset_index()

print(df2.shape)
print(df2.head())

(457, 19)
  AREOPORTO_PARTENZA AREOPORTO_ARRIVO  tot_entrati  tot_investigati  \
0                abj              cag          1.0              1.0   
1                adb              bgy          1.0              1.0   
2                adb              fco          1.0              1.0   
3                adb              mxp          5.0              5.0   
4                adb              nap          2.0              2.0   

   tot_allarmati  n_record  tasso_allarme  alert_rate_alb  alert_rate_afg  \
0            0.0       1.0            0.0             NaN             NaN   
1            0.0       1.0            0.0             0.0             NaN   
2            1.0       1.0            1.0             NaN             NaN   
3            2.0       4.0            0.4             0.0             NaN   
4            0.0       1.0            0.0             0.0             NaN   

   pct_naz_alb  pct_naz_afg  alert_rate_visto  alert_rate_passaporto  \
0         0.00          0.0 

In [887]:
df_finale = df1.merge(
    df2,
    on=['AREOPORTO_PARTENZA', 'AREOPORTO_ARRIVO'],
    how='left',
    suffixes=('_allarmi', '_tip')
)

print(f'Rotte totali:  {len(df_finale)}')
print(f'Con match:     {df_finale["tot_entrati"].notna().sum()} ({100*df_finale["tot_entrati"].notna().mean():.1f}%)')
print(f'Shape finale:  {df_finale.shape}')
print()
print(df_finale.isnull().sum().to_string())

Rotte totali:  366
Con match:     265 (72.4%)
Shape finale:  (366, 38)

AREOPORTO_PARTENZA               0
AREOPORTO_ARRIVO                 0
tot_allarmi_chiusi               0
tot_allarmi_generati             0
tot_allarmi_non_chiusi           0
tot_allarmi_rilevanti            0
tot_altro                        0
tot_esito_negativo               0
tot_mancato_aggiornamento        0
tot_viaggiatori_con_allarmi      0
tot_viaggiatori_entrati          0
tot_viaggiatori_investigati      0
tot_voli_con_allarmi             0
tot_voli_disponibili             0
tot_voli_investigati             0
tot_voli_solo_visualizzati       0
CITTA_ARR                        0
CITTA_PARTENZA                   0
PAESE_PART                       0
ZONA                             0
MOTIVO_ALLARME                  16
tot_entrati                    101
tot_investigati                101
tot_allarmati                  101
n_record                       101
tasso_allarme                  104
alert_rate_alb    

In [888]:
df_finale

,AREOPORTO_PARTENZA,AREOPORTO_ARRIVO,tot_allarmi_chiusi,tot_allarmi_generati,tot_allarmi_non_chiusi,tot_allarmi_rilevanti,tot_altro,tot_esito_negativo,tot_mancato_aggiornamento,tot_viaggiatori_con_allarmi,...,pct_naz_alb,pct_naz_afg,alert_rate_visto,alert_rate_passaporto,alert_rate_permesso,alert_rate_carta,pct_segnalato,pct_respinto,pct_fermato,pct_ok
0,adb,mxp,0,5,0,0,0,0,0,3,...,0.750,0.0,0.666667,NaN,NaN,0.0,0.000000,0.250000,0.250000,0.250000
1,add,fco,46,20,0,1,0,0,0,13,...,0.000,0.0,0.000000,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000
2,add,mxp,52,197,0,0,0,0,0,30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,aga,bgy,0,16,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ala,mxp,0,1,0,0,0,0,0,0,...,0.000,1.0,NaN,0.0,NaN,NaN,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,yul,mxp,0,0,0,0,0,3,0,7,...,1.000,0.0,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
362,yyz,fco,6,1,0,0,0,0,0,0,...,0.700,0.0,0.142857,NaN,NaN,0.0,0.333333,0.333333,0.111111,0.222222
363,yyz,mxp,0,0,0,0,0,0,0,0,...,1.000,0.0,NaN,0.0,0.0,0.0,0.500000,0.000000,0.250000,0.000000
364,znz,fco,22,0,0,0,0,0,0,0,...,0.875,0.0,0.500000,1.0,0.0,0.0,0.285714,0.142857,0.000000,0.428571


In [889]:
df_model = df_finale.copy()
print(f'Rotte totali: {len(df_model)}')

# Imputa con 0 — assenza del fenomeno
cols_zero = [
    'alert_rate_alb', 'alert_rate_afg',
    'pct_naz_alb', 'pct_naz_afg',
    'alert_rate_visto', 'alert_rate_passaporto',
    'alert_rate_permesso', 'alert_rate_carta',
    'pct_segnalato', 'pct_respinto', 'pct_fermato', 'pct_ok',
    'tot_entrati', 'tot_investigati', 'tot_allarmati',
    'n_record'
]
df_model[cols_zero] = df_model[cols_zero].fillna(0)

# Imputa tasso_allarme con mediana
mediana_tasso = df_model['tasso_allarme'].median()
df_model['tasso_allarme'] = df_model['tasso_allarme'].fillna(mediana_tasso)

print('NaN residui:')
print(df_model.isnull().sum()[df_model.isnull().sum() > 0].to_string())
print(f'\nShape: {df_model.shape}')

Rotte totali: 366
NaN residui:
MOTIVO_ALLARME    16

Shape: (366, 38)


In [890]:
df_model

,AREOPORTO_PARTENZA,AREOPORTO_ARRIVO,tot_allarmi_chiusi,tot_allarmi_generati,tot_allarmi_non_chiusi,tot_allarmi_rilevanti,tot_altro,tot_esito_negativo,tot_mancato_aggiornamento,tot_viaggiatori_con_allarmi,...,pct_naz_alb,pct_naz_afg,alert_rate_visto,alert_rate_passaporto,alert_rate_permesso,alert_rate_carta,pct_segnalato,pct_respinto,pct_fermato,pct_ok
0,adb,mxp,0,5,0,0,0,0,0,3,...,0.750,0.0,0.666667,0.0,0.0,0.0,0.000000,0.250000,0.250000,0.250000
1,add,fco,46,20,0,1,0,0,0,13,...,0.000,0.0,0.000000,0.0,0.0,0.0,1.000000,0.000000,0.000000,0.000000
2,add,mxp,52,197,0,0,0,0,0,30,...,0.000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
3,aga,bgy,0,16,0,0,0,0,0,0,...,0.000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
4,ala,mxp,0,1,0,0,0,0,0,0,...,0.000,1.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,yul,mxp,0,0,0,0,0,3,0,7,...,1.000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
362,yyz,fco,6,1,0,0,0,0,0,0,...,0.700,0.0,0.142857,0.0,0.0,0.0,0.333333,0.333333,0.111111,0.222222
363,yyz,mxp,0,0,0,0,0,0,0,0,...,1.000,0.0,0.000000,0.0,0.0,0.0,0.500000,0.000000,0.250000,0.000000
364,znz,fco,22,0,0,0,0,0,0,0,...,0.875,0.0,0.500000,1.0,0.0,0.0,0.285714,0.142857,0.000000,0.428571


# DATA PREPARATION

### Feature Selection e Scaling

Si selezionano le 30 features numeriche estratte dai due dataset — 14 da df1 
(metriche operative sugli allarmi) e 16 da df2 (tassi di allarme per nazionalità, 
tipo documento ed esito controllo).

Poiché la distribuzione è **zero-inflated** — la maggior parte delle rotte ha 
valore 0 su molte features — si applica una trasformazione logaritmica `log(x+1)` 
prima dello scaling. Questo comprime i valori estremi e rende la distribuzione 
più simmetrica senza perdere informazione sugli zeri.

Si utilizza **StandardScaler** come baseline cross-sezionale: ogni valore viene 
trasformato in "deviazioni standard dalla media globale delle 366 rotte". 
Il risultato è una matrice `X_scaled` dove valori positivi indicano rotte 
al di sopra della media, valori negativi al di sotto.

In [891]:
from sklearn.preprocessing import StandardScaler

feature_cols = [
    'tot_allarmi_chiusi', 'tot_allarmi_generati', 'tot_allarmi_non_chiusi',
    'tot_allarmi_rilevanti', 'tot_altro', 'tot_esito_negativo',
    'tot_mancato_aggiornamento', 'tot_viaggiatori_con_allarmi',
    'tot_viaggiatori_entrati', 'tot_viaggiatori_investigati',
    'tot_voli_con_allarmi', 'tot_voli_disponibili',
    'tot_voli_investigati', 'tot_voli_solo_visualizzati',
    'tot_entrati', 'tot_investigati', 'tot_allarmati',
    'tasso_allarme', 'alert_rate_alb', 'alert_rate_afg',
    'pct_naz_alb', 'pct_naz_afg', 'alert_rate_visto',
    'alert_rate_passaporto', 'alert_rate_permesso', 'alert_rate_carta',
    'pct_segnalato', 'pct_respinto', 'pct_fermato', 'pct_ok'
]

X = df_model[feature_cols].copy()

# Log(x+1): comprime i valori estremi, gestisce la distribuzione zero-inflated
X_log = np.log1p(X)

# StandardScaler: costruisce la baseline cross-sezionale
# Ogni valore diventa "deviazioni standard dalla media globale"
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_log)
X_scaled = pd.DataFrame(X_scaled, columns=feature_cols, index=df_model.index)

print(f'Shape X_scaled: {X_scaled.shape}')
print(f'Media (attesa ~0): {X_scaled.mean().mean():.4f}')
print(f'Std  (attesa ~1):  {X_scaled.std().mean():.4f}')
print()
print(X_scaled.describe().round(2).to_string())

Shape X_scaled: (366, 30)
Media (attesa ~0): -0.0000
Std  (attesa ~1):  1.0014

       tot_allarmi_chiusi  tot_allarmi_generati  tot_allarmi_non_chiusi  tot_allarmi_rilevanti  tot_altro  tot_esito_negativo  tot_mancato_aggiornamento  tot_viaggiatori_con_allarmi  tot_viaggiatori_entrati  tot_viaggiatori_investigati  tot_voli_con_allarmi  tot_voli_disponibili  tot_voli_investigati  tot_voli_solo_visualizzati  tot_entrati  tot_investigati  tot_allarmati  tasso_allarme  alert_rate_alb  alert_rate_afg  pct_naz_alb  pct_naz_afg  alert_rate_visto  alert_rate_passaporto  alert_rate_permesso  alert_rate_carta  pct_segnalato  pct_respinto  pct_fermato  pct_ok
count              366.00                366.00                  366.00                 366.00     366.00              366.00                     366.00                       366.00                   366.00                       366.00                366.00                366.00                366.00                      366.00       366.00

Lo scaling produce una matrice `(366, 30)` con media ~0 e std ~1 su tutte 
le features — confermando che la baseline cross-sezionale è stata costruita 
correttamente.

Si nota che alcune features come `tot_allarmi_non_chiusi` e 
`tot_mancato_aggiornamento` hanno valori molto compressi (max vicino a 0) — 
sintomo di distribuzione quasi costante con pochissime rotte > 0. 
Queste features verranno rivalutate prima della fase di Anomaly Detection.

### Baseline Cross-Sezionale

Per ogni feature si calcola la distribuzione statistica sull'intera popolazione 
delle 366 rotte: media e deviazione standard nello spazio log-trasformato, 
e i percentili chiave (mediana, p75, p90, p95) nei valori originali.

Questa baseline serve come riferimento per il post processing: le soglie delle 
regole (es. "tasso di allarme supera 3x la baseline") vengono derivate 
direttamente da questi valori, in particolare dalla mediana.

In [892]:
# Baseline cross-sezionale: media e std di ogni feature dopo log transform
baseline = pd.DataFrame({
    'feature': feature_cols,
    'media_log': np.log1p(df_model[feature_cols]).mean().values,
    'std_log': np.log1p(df_model[feature_cols]).std().values,
    'mediana_originale': df_model[feature_cols].median().values,
    'p75_originale': df_model[feature_cols].quantile(0.75).values,
    'p90_originale': df_model[feature_cols].quantile(0.90).values,
    'p95_originale': df_model[feature_cols].quantile(0.95).values,
})

print('=== BASELINE CROSS-SEZIONALE ===')
print(baseline.to_string())

=== BASELINE CROSS-SEZIONALE ===
                        feature  media_log   std_log  mediana_originale  p75_originale  p90_originale  p95_originale
0            tot_allarmi_chiusi   1.030789  1.495675                0.0            8.0           27.5           49.0
1          tot_allarmi_generati   1.418175  1.690862                0.0          17.75           56.0           91.5
2        tot_allarmi_non_chiusi   0.013579  0.108138                0.0            0.0            0.0            0.0
3         tot_allarmi_rilevanti   0.203865  0.497942                0.0            0.0            1.0            3.0
4                     tot_altro   0.040942  0.289576                0.0            0.0            0.0            0.0
5            tot_esito_negativo   0.988148  1.427471                0.0            7.0           28.0          39.75
6     tot_mancato_aggiornamento   0.015151   0.10149                0.0            0.0            0.0            0.0
7   tot_viaggiatori_con_allarmi

La baseline evidenzia alcune caratteristiche importanti della distribuzione:

- **Features quasi sempre a zero** — `tot_allarmi_non_chiusi`, `tot_altro` e 
  `tot_mancato_aggiornamento` hanno mediana e p90 pari a 0, confermando che 
  sono eventi rarissimi nel dataset.

- **Alta variabilità nei volumi** — `tot_viaggiatori_entrati` va da una mediana 
  di 189 a un p95 di 1226, e `tot_entrati` da 6 a 4396 al p95. Il log transform 
  era necessario per gestire questa dispersione.

- **Soglia operativa per tasso_allarme** — mediana 0.175, p90 = 0.5. 
  La regola "3x baseline" corrisponde a una soglia di **0.525**, usata nel 
  post processing per flaggare le rotte ad alto rischio.

- **Dominanza albanese** — `pct_naz_alb` ha mediana 0.944, confermando che 
  la quasi totalità dei passeggeri allarmati è di nazionalità albanese. 
  Questa concentrazione va tenuta presente nell'interpretazione dei risultati.